// Photoreal r2 (lane Photoreal r2): a second round of photoreal captures, one SOG pair each
// (assets/toys/<id>/<id>.sog and -lite.sog, made by tools/pr2-prepare.mjs from the sources in
// tools/assets.json). Metadata only: the toys are captured scans, so there is no toy code. All of
// them are behind the labs switch until the owner marks them good. A tap hops them (no part of a
// capture moves cleanly), and each has its own sound in src/toy-sounds.js.
//
// Three captures are NonCommercial (CC BY-NC or CC BY-NC-SA, the owner's call of October 3, 2026):
// they carry `"nc": true` in tools/assets.json, and `node tools/nc-assets.mjs` lists them.

export const PHOTOREAL_R2_TOYS = [
  {
    id: "heart-donut",
    label: "Heart donut",
    category: "scans",
    tags: "photoreal scan captured food pastry doughnut sweet dessert glaze",
    kind: "captured",
    labs: true,
    url: "assets/toys/heart-donut/heart-donut.sog",
    urlWeak: "assets/toys/heart-donut/heart-donut-lite.sog",
    credit: {
      title: "Heart Shaped Donut",
      author: "John Splat",
      source: "https://superspl.at/scene/d2a622ec",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "sushi-boat",
    label: "Sushi boat",
    category: "scans",
    tags: "photoreal scan captured food sushi fish rice japanese wooden boat",
    kind: "captured",
    labs: true,
    url: "assets/toys/sushi-boat/sushi-boat.sog",
    urlWeak: "assets/toys/sushi-boat/sushi-boat-lite.sog",
    credit: {
      title: "SUSHI",
      author: "leo esteves",
      source: "https://superspl.at/scene/43ddc643",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "seeded-loaf",
    label: "Seeded bread loaf",
    category: "scans",
    tags: "photoreal scan captured food bread bakery loaf seeds",
    kind: "captured",
    labs: true,
    url: "assets/toys/seeded-loaf/seeded-loaf.sog",
    urlWeak: "assets/toys/seeded-loaf/seeded-loaf-lite.sog",
    credit: {
      title: "Seeded Bread Loaf",
      author: "John Splat",
      source: "https://superspl.at/scene/e1beac1a",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "steak",
    label: "Cowboy steak",
    category: "scans",
    tags: "photoreal scan captured food steak meat grilled beef",
    kind: "captured",
    labs: true,
    url: "assets/toys/steak/steak.sog",
    urlWeak: "assets/toys/steak/steak-lite.sog",
    credit: {
      title: "Cowboy Steak",
      author: "Eric Cornwell",
      source: "https://superspl.at/scene/6e60e106",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "stollen",
    label: "Stollen",
    category: "scans",
    tags: "photoreal scan captured food bread christmas german sweet fruit powdered sugar",
    kind: "captured",
    labs: true,
    url: "assets/toys/stollen/stollen.sog",
    urlWeak: "assets/toys/stollen/stollen-lite.sog",
    credit: {
      title: "Stollen Confectionery",
      author: "Dany Bittel",
      source: "https://superspl.at/scene/070d50b8",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "orange-photo",
    label: "Orange (photo)",
    category: "scans",
    tags: "photoreal scan captured food fruit citrus orange peel real",
    kind: "captured",
    labs: true,
    url: "assets/toys/orange-photo/orange-photo.sog",
    urlWeak: "assets/toys/orange-photo/orange-photo-lite.sog",
    credit: {
      title: "Fresh Orange",
      author: "Storm Geerling",
      source: "https://superspl.at/scene/633ea98d",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "physalis",
    label: "Physalis",
    category: "scans",
    tags: "photoreal scan captured plant fruit lantern husk cape gooseberry",
    kind: "captured",
    labs: true,
    url: "assets/toys/physalis/physalis.sog",
    urlWeak: "assets/toys/physalis/physalis-lite.sog",
    credit: {
      title: "Physalis",
      author: "Alfred Duemlein",
      source: "https://superspl.at/scene/908ed1a1",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "crystal-gem",
    label: "Crystal",
    category: "scans",
    tags: "photoreal scan captured gem crystal quartz mineral clear shiny",
    kind: "captured",
    labs: true,
    url: "assets/toys/crystal-gem/crystal-gem.sog",
    urlWeak: "assets/toys/crystal-gem/crystal-gem-lite.sog",
    credit: {
      title: "Homemade Crystal Gem",
      author: "Eric Cornwell",
      source: "https://superspl.at/scene/6cca7765",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "alum-crystal",
    label: "Alum crystal",
    category: "scans",
    tags: "photoreal scan captured gem crystal alum mineral pink salt deodorant",
    kind: "captured",
    labs: true,
    url: "assets/toys/alum-crystal/alum-crystal.sog",
    urlWeak: "assets/toys/alum-crystal/alum-crystal-lite.sog",
    credit: {
      title: "alum-stone",
      author: "Arshad",
      source: "https://superspl.at/scene/9b0c8534",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes: "Converted, decimated, recentred and scaled. The source has no spherical harmonics.",
    },
  },
  {
    id: "puffin",
    label: "Puffin",
    category: "scans",
    tags: "photoreal scan captured animal bird puffin seabird figurine",
    kind: "captured",
    labs: true,
    url: "assets/toys/puffin/puffin.sog",
    urlWeak: "assets/toys/puffin/puffin-lite.sog",
    credit: {
      title: "Puffin",
      author: "Dan Zeitman",
      source: "https://superspl.at/scene/d44e63ab",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "toy-trex",
    label: "Toy T. rex",
    category: "scans",
    tags: "photoreal scan captured toy dinosaur trex rubber figure",
    kind: "captured",
    labs: true,
    url: "assets/toys/toy-trex/toy-trex.sog",
    urlWeak: "assets/toys/toy-trex/toy-trex-lite.sog",
    credit: {
      title: "Tyrannosaurus Rex",
      author: "Alfred Duemlein",
      source: "https://superspl.at/scene/d281a49d",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "monkey-doll",
    label: "Monkey doll",
    category: "scans",
    tags: "photoreal scan captured toy plush monkey doll soft stuffed",
    kind: "captured",
    labs: true,
    url: "assets/toys/monkey-doll/monkey-doll.sog",
    urlWeak: "assets/toys/monkey-doll/monkey-doll-lite.sog",
    credit: {
      title: "Monkey Doll",
      author: "Ethan",
      source: "https://superspl.at/scene/726c5f45",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes: "Converted, decimated, recentred and scaled. The source has no spherical harmonics.",
    },
  },
  {
    id: "elephant-souvenir",
    label: "Souvenir elephant",
    category: "scans",
    tags: "photoreal scan captured animal elephant souvenir statue figurine thai",
    kind: "captured",
    labs: true,
    url: "assets/toys/elephant-souvenir/elephant-souvenir.sog",
    urlWeak: "assets/toys/elephant-souvenir/elephant-souvenir-lite.sog",
    credit: {
      title: "Thai souvenir elephant toy",
      author: "Aung Sann Thit",
      source: "https://superspl.at/scene/b01bfc43",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "turtle-souvenir",
    label: "Souvenir turtle",
    category: "scans",
    tags: "photoreal scan captured animal turtle sea souvenir statue figurine",
    kind: "captured",
    labs: true,
    url: "assets/toys/turtle-souvenir/turtle-souvenir.sog",
    urlWeak: "assets/toys/turtle-souvenir/turtle-souvenir-lite.sog",
    credit: {
      title: "Turtle Souvenir",
      author: "Tony Rose",
      source: "https://superspl.at/scene/c2051d75",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "cave-lioness",
    label: "Cave lioness",
    category: "scans",
    tags: "photoreal scan captured animal lion lioness cave museum cat",
    kind: "captured",
    labs: true,
    url: "assets/toys/cave-lioness/cave-lioness.sog",
    urlWeak: "assets/toys/cave-lioness/cave-lioness-lite.sog",
    credit: {
      title: "Lioness (Panthera Spelaea)",
      author: "Spenser DIckerson",
      source: "https://superspl.at/scene/7e4e9bcb",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "dog-plush",
    label: "Dog plush",
    category: "scans",
    tags: "photoreal scan captured toy plush dog doll soft stuffed",
    kind: "captured",
    labs: true,
    url: "assets/toys/dog-plush/dog-plush.sog",
    urlWeak: "assets/toys/dog-plush/dog-plush-lite.sog",
    credit: {
      title: "Dog Plush - Revopoint POP4 with additional Pictures",
      author: "PrintedForFun",
      source: "https://superspl.at/scene/55d00502",
      license: "CC BY-NC 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-nc/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "bmx-bike",
    label: "BMX bicycle",
    category: "scans",
    tags: "photoreal scan captured vehicle bicycle bike bmx wheels",
    kind: "captured",
    labs: true,
    url: "assets/toys/bmx-bike/bmx-bike.sog",
    urlWeak: "assets/toys/bmx-bike/bmx-bike-lite.sog",
    credit: {
      title: "BMX Bicycle - Enhanced",
      author: "Eric Cornwell",
      source: "https://superspl.at/scene/e95011f3",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "murex-shell",
    label: "Murex shell",
    category: "scans",
    tags: "photoreal scan captured shell nature sea snail spines venus comb",
    kind: "captured",
    labs: true,
    url: "assets/toys/murex-shell/murex-shell.sog",
    urlWeak: "assets/toys/murex-shell/murex-shell-lite.sog",
    credit: {
      title: "Murex Shell",
      author: "Rigsters",
      source: "https://superspl.at/scene/d55ecb52",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "sunflower-photo",
    label: "Sunflower (photo)",
    category: "scans",
    tags: "photoreal scan captured plant flower sunflower yellow seeds real",
    kind: "captured",
    labs: true,
    url: "assets/toys/sunflower-photo/sunflower-photo.sog",
    urlWeak: "assets/toys/sunflower-photo/sunflower-photo-lite.sog",
    credit: {
      title: "Sunflower ",
      author: "Natural Ai",
      source: "https://superspl.at/scene/d8c22218",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "white-roses",
    label: "White roses",
    category: "scans",
    tags: "photoreal scan captured plant flower roses vase white bouquet",
    kind: "captured",
    labs: true,
    url: "assets/toys/white-roses/white-roses.sog",
    urlWeak: "assets/toys/white-roses/white-roses-lite.sog",
    credit: {
      title: "White Rose 2",
      author: "Natural Ai",
      source: "https://superspl.at/scene/e34ad55d",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "bonsai-photo",
    label: "Bonsai tree (photo)",
    category: "scans",
    tags: "photoreal scan captured plant tree bonsai garden japanese real",
    kind: "captured",
    labs: true,
    url: "assets/toys/bonsai-photo/bonsai-photo.sog",
    urlWeak: "assets/toys/bonsai-photo/bonsai-photo-lite.sog",
    credit: {
      title: "Bonsai Tree",
      author: "Garrett Nelli",
      source: "https://superspl.at/scene/4c461e7c",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "mushroom-photo",
    label: "Mushroom (photo)",
    category: "scans",
    tags: "photoreal scan captured nature mushroom fungus forest floor real",
    kind: "captured",
    labs: true,
    url: "assets/toys/mushroom-photo/mushroom-photo.sog",
    urlWeak: "assets/toys/mushroom-photo/mushroom-photo-lite.sog",
    credit: {
      title: "Rugiboletus extremiorientalis mushroom",
      author: "Alexander Omelko",
      source: "https://superspl.at/scene/737cf53c",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "cactus-real",
    label: "Cactus (photo 2)",
    category: "scans",
    tags: "photoreal scan captured plant cactus succulent spines real desert",
    kind: "captured",
    labs: true,
    url: "assets/toys/cactus-real/cactus-real.sog",
    urlWeak: "assets/toys/cactus-real/cactus-real-lite.sog",
    credit: {
      title: "Cactus 1",
      author: "Natural Ai",
      source: "https://superspl.at/scene/4e095e21",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "crochet-earth",
    label: "Crochet Earth",
    category: "scans",
    tags: "photoreal scan captured space earth planet crochet craft world globe",
    kind: "captured",
    labs: true,
    url: "assets/toys/crochet-earth/crochet-earth.sog",
    urlWeak: "assets/toys/crochet-earth/crochet-earth-lite.sog",
    credit: {
      title: "Earth Crochet from Project Hail Mary",
      author: "Wan Xi",
      source: "https://superspl.at/scene/8d1a69d2",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "desk-globe",
    label: "Desk globe",
    category: "scans",
    tags: "photoreal scan captured space earth globe map geography school desk",
    kind: "captured",
    labs: true,
    url: "assets/toys/desk-globe/desk-globe.sog",
    urlWeak: "assets/toys/desk-globe/desk-globe-lite.sog",
    credit: {
      title: "Cheap globe",
      author: "ilk",
      source: "https://superspl.at/scene/9e8174d2",
      license: "CC BY-NC 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-nc/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "cherry-blossom-photo",
    label: "Cherry blossom (photo)",
    category: "scans",
    tags: "photoreal scan captured nature tree cherry blossom spring flowers pink real",
    kind: "captured",
    labs: true,
    url: "assets/toys/cherry-blossom-photo/cherry-blossom-photo.sog",
    urlWeak: "assets/toys/cherry-blossom-photo/cherry-blossom-photo-lite.sog",
    credit: {
      title: "CHERRY BLOSSOM - HIGH PARK",
      author: "Todd Smith",
      source: "https://superspl.at/scene/4eec644f",
      license: "CC BY-NC-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "maple-tree",
    label: "Golden maple",
    category: "scans",
    tags: "photoreal scan captured nature tree maple autumn garden shrub real",
    kind: "captured",
    labs: true,
    url: "assets/toys/maple-tree/maple-tree.sog",
    urlWeak: "assets/toys/maple-tree/maple-tree-lite.sog",
    credit: {
      title: "Golden Fullmoon Maple",
      author: "Joshua Trapani",
      source: "https://superspl.at/scene/f233b115",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "peony",
    label: "Peonies in a vase",
    category: "scans",
    tags: "photoreal scan captured plant flower peony vase pink bouquet",
    kind: "captured",
    labs: true,
    url: "assets/toys/peony/peony.sog",
    urlWeak: "assets/toys/peony/peony-lite.sog",
    credit: {
      title: "Pink Peonies",
      author: "Sergiu Zboras",
      source: "https://superspl.at/scene/50c8ccf7",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "money-tree",
    label: "Money tree",
    category: "scans",
    tags: "photoreal scan captured plant houseplant pachira pot tree green",
    kind: "captured",
    labs: true,
    url: "assets/toys/money-tree/money-tree.sog",
    urlWeak: "assets/toys/money-tree/money-tree-lite.sog",
    credit: {
      title: "Money Tree (Pachira)",
      author: "Natural Ai",
      source: "https://superspl.at/scene/45d3761b",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
  {
    id: "knight-horse",
    label: "Knight on a horse",
    category: "scans",
    tags: "photoreal scan captured toy knight horse medieval figure miniature sword armor",
    kind: "captured",
    labs: true,
    url: "assets/toys/knight-horse/knight-horse.sog",
    urlWeak: "assets/toys/knight-horse/knight-horse-lite.sog",
    credit: {
      title: "A knight with a sword and shield on a black horse",
      author: "Alfred Duemlein",
      source: "https://superspl.at/scene/2d074d8a",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, recentred and scaled. One band of spherical harmonics kept on the full file.",
    },
  },
];
