// Lane QR lab r2, the study of splat QR codes: "Do codes have to be
// square?" (item 4), part two: the standard's other shapes. Micro QR
// (ISO/IEC 18004, a smaller square with one finder) and rMQR (rectangular
// Micro QR, ISO/IEC 23941:2022) are generated by two independent writers,
// zxing-cpp (zxing-wasm) and BWIPP (bwip-js), drawn as plain pixels and as
// splats, photographed as in the sweeps and read by the three readers.
// A standard QR code of the same text is the control. Writes micro.csv and
// a picture of each in micro/.
import fs from "node:fs";
import path from "node:path";
import bwipjs from "bwip-js";
import { writeBarcode } from "zxing-wasm/full";
import { codeSplats } from "../../src/qr-lab/splats.js";
import { applyCondition, conditions, newImage, resize } from "../qr-scan-lab/sim.mjs";
import { render, screenCamera, toPNG } from "./raster.mjs";
import { CONDITIONS, toCSV } from "./core.mjs";
import { initZxingCpp, readAll, zxingCppAll, READERS } from "./readers.mjs";
import { rng } from "../../src/qr-lab/damage.js";

const CASES = [
  { id: "micro-alnum", format: "MicroQRCode", bcid: "microqrcode", text: "HELLO 123" },
  { id: "micro-bytes", format: "MicroQRCode", bcid: "microqrcode", text: "Splats!" },
  { id: "rmqr-url", format: "RMQRCode", bcid: "rectangularmicroqrcode", text: "https://ryanjosephkamp.github.io/splashery/" }, // prettier-ignore
  { id: "rmqr-short", format: "RMQRCode", bcid: "rectangularmicroqrcode", text: "Splats make a code!" }, // prettier-ignore
  { id: "qr-url", format: "QRCode", bcid: "qrcode", text: "https://ryanjosephkamp.github.io/splashery/" }, // prettier-ignore
];
const QUIET = 2; // Micro QR and rMQR ask for 2 modules; the control QR gets 4

// A matrix { w, h, dark: Uint8Array (1 dark) } from each writer.
async function fromZxing(c) {
  await initZxingCpp();
  const r = await writeBarcode(c.text, { format: c.format, ecLevel: c.format === "QRCode" ? "M" : undefined }); // prettier-ignore
  if (r.error) throw new Error(r.error);
  const s = r.symbol;
  return { w: s.width, h: s.height, dark: Uint8Array.from(s.data, (v) => (v < 128 ? 1 : 0)) };
}
function fromBwip(c, like) {
  const opts = c.format === "RMQRCode" ? `version=R${like.h}x${like.w} eclevel=M` : c.format === "MicroQRCode" ? `version=M${(like.w - 9) / 2}` : "eclevel=M"; // prettier-ignore
  const r = bwipjs.raw(c.bcid, c.text, opts)[0];
  return { w: r.pixx, h: r.pixy, dark: Uint8Array.from(r.pixs) };
}

// Plain pixels: `ppm` per module, a quiet zone of q modules, on white.
function pixels(m, q, ppm = 8) {
  const W = (m.w + 2 * q) * ppm;
  const H = (m.h + 2 * q) * ppm;
  const img = newImage(W, H);
  for (let y = 0; y < m.h; y++)
    for (let x = 0; x < m.w; x++)
      if (m.dark[y * m.w + x])
        for (let j = 0; j < ppm; j++)
          for (let i = 0; i < ppm; i++) img.data.set([18, 20, 26], (((y + q) * ppm + j) * W + (x + q) * ppm + i) * 4); // prettier-ignore
  return img;
}
// As splats: codeSplats takes a square, so the matrix sits in a square of
// light modules (more quiet zone above and below an rMQR, never less).
function splatted(m, q, trial) {
  const N = Math.max(m.w, m.h);
  const mods = new Uint8Array(N * N);
  const ox = Math.floor((N - m.w) / 2);
  const oy = Math.floor((N - m.h) / 2);
  for (let y = 0; y < m.h; y++) for (let x = 0; x < m.w; x++) mods[(y + oy) * N + x + ox] = m.dark[y * m.w + x]; // prettier-ignore
  // Center the symbol, and keep only the sheet within its own quiet zone.
  const sx = ox + m.w / 2 - N / 2;
  const sy = N / 2 - (oy + m.h / 2);
  const hx = m.w / 2 + q;
  const hy = m.h / 2 + q;
  const sp = codeSplats(mods, N, { quiet: q })
    .map((s) => ({ ...s, p: [s.p[0] - sx, s.p[1] - sy, s.p[2]] }))
    .filter((s) => s.mod >= 0 || (Math.abs(s.p[0]) <= hx && Math.abs(s.p[1]) <= hy));
  const tall = Math.round((m.h + 2 * q) * 1.2);
  const wide = Math.round((m.w + 2 * q) * 1.2);
  const r = rng(trial * 7919 + 3);
  const cam = screenCamera(tall, { ppm: 8, offset: [r() - 0.5, r() - 0.5], aspect: wide / tall });
  return { img: render(sp, cam), wide };
}

export async function runMicro(out, { trials = 5 } = {}) {
  const dir = path.join(out, "micro");
  fs.mkdirSync(dir, { recursive: true });
  const rows = [];
  const t0 = Date.now();
  for (const c of CASES) {
    const zx = await fromZxing(c);
    let bw = null;
    try {
      bw = fromBwip(c, zx);
    } catch (e) {
      console.log(`  bwip-js ${c.id}: ${e.message}`);
    }
    const same = bw && bw.w === zx.w && bw.h === zx.h && bw.dark.every((v, i) => v === zx.dark[i]);
    for (const [writer, m] of [
      ["zxing-cpp", zx],
      ["bwip-js", bw],
    ]) {
      if (!m) continue;
      const q = c.format === "QRCode" ? 4 : QUIET;
      for (const how of ["pixels", "splats"])
        for (let trial = 0; trial < trials; trial++) {
          let img;
          let wide;
          if (how === "pixels") {
            img = pixels(m, q);
            wide = m.w + 2 * q;
          } else ({ img, wide } = splatted(m, q, trial));
          if (trial === 0) fs.writeFileSync(path.join(dir, `${c.id}-${writer}-${how}.png`), toPNG(img.width > 320 ? resize(img, 320) : img, { step: 8 })); // prettier-ignore
          // Plain pixels: every capture of the scan lab, once. Splats: the
          // study's three captures, each trial.
          if (how === "pixels" && trial > 0) continue;
          for (const cond of how === "pixels" ? conditions() : CONDITIONS) {
            const photo = applyCondition(img, wide, cond, 7 + trial * 101 + cond.id.length);
            const got = await readAll(photo);
            const fmt = (await zxingCppAll(photo)).find((x) => x.text === c.text)?.format ?? "";
            const row = { case: c.id, format: c.format, size: `${m.w}x${m.h}`, writer, writersAgree: same ? 1 : 0, how, trial, cond: cond.id, zxingcppFormat: fmt }; // prettier-ignore
            for (const r of READERS) row[r] = got[r] === c.text ? 1 : 0;
            rows.push(row);
          }
        }
    }
  }
  fs.writeFileSync(path.join(out, "micro-raw.csv"), toCSV(rows, ["case", "format", "size", "writer", "writersAgree", "how", "trial", "cond", ...READERS, "zxingcppFormat"])); // prettier-ignore
  const sum = [];
  const keys = new Set(rows.map((r) => `${r.case}|${r.writer}|${r.how}|${r.cond}`));
  for (const k of keys) {
    const rs = rows.filter((r) => `${r.case}|${r.writer}|${r.how}|${r.cond}` === k);
    const row = { case: rs[0].case, format: rs[0].format, size: rs[0].size, writer: rs[0].writer, writersAgree: rs[0].writersAgree, how: rs[0].how, cond: rs[0].cond, n: rs.length }; // prettier-ignore
    for (const r of READERS) row[r] = rs.reduce((s, x) => s + x[r], 0);
    row.zxingcppFormat = [...new Set(rs.map((r) => r.zxingcppFormat).filter(Boolean))].join(" ");
    sum.push(row);
  }
  fs.writeFileSync(path.join(out, "micro.csv"), toCSV(sum, ["case", "format", "size", "writer", "writersAgree", "how", "cond", "n", ...READERS, "zxingcppFormat"])); // prettier-ignore
  console.log(`micro: ${rows.length} captures in ${((Date.now() - t0) / 1000).toFixed(0)} s`);
  return sum;
}
