#!/usr/bin/env node
// Lane Photoreal r3: a captured toy's underside, measured from its splats in world coordinates
// (.cache/pr3/<id>-world.bin, written by tools/pr3-measure.mjs), for the kit-built bases in
// src/packs/photoreal-r3-rigs.js.
//
//   node tools/pr3-under.mjs <id> [--band=y0,y1] [--box=x0,x1,z0,z1] [--n=48] [--hist]
//
// For the opaque splats in the band (and box): their center on the ground, a plane fitted to the
// lowest of them (y = a + b x + c z), their outline as a radius at n angles round that center
// (from +x toward +z), and their median color. --hist prints how many splats sit at each height,
// to find a mat's top and bottom.
//
//   node tools/pr3-under.mjs --all
//
// measures every outline in tools/pr3-bases.json ({ name: { id, band, box?, n?, smooth? } }) and
// writes src/packs/photoreal-r3-bases.js, which the rigs read.

import fs from "node:fs";
import path from "node:path";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const args = process.argv.slice(2);
const opt = (name, def) => {
  const a = args.find((x) => x.startsWith(`--${name}=`));
  return a ? a.slice(name.length + 3) : def;
};
if (args.includes("--all")) {
  const { execFileSync } = await import("node:child_process");
  const specs = JSON.parse(fs.readFileSync(path.join(root, "tools/pr3-bases.json"), "utf8"));
  const lines = [];
  for (const [name, s] of Object.entries(specs)) {
    const a = [
      path.join(root, "tools/pr3-under.mjs"),
      s.id,
      `--band=${s.band}`,
      `--n=${s.n ?? 48}`,
    ];
    if (s.box) a.push(`--box=${s.box}`);
    if (s.top) a.push(`--top=${s.top}`);
    const j = JSON.parse(execFileSync("node", a, { encoding: "utf8" }));
    lines.push(`  ${JSON.stringify(name)}: ${JSON.stringify({ center: j.center, plane: j.plane, lowest: j.lowest, color: j.color, radii: j.radii, rect: j.rect, top: j.top })},`); // prettier-ignore
  }
  const out = `// Generated by tools/pr3-under.mjs --all from tools/pr3-bases.json (lane Photoreal r3): each
// toy's underside outline in world coordinates, for src/packs/photoreal-r3-rigs.js. Don't edit by hand.

export const PR3_BASES = {
${lines.join("\n")}
};
`;
  fs.writeFileSync(path.join(root, "src/packs/photoreal-r3-bases.js"), out);
  console.log(`${lines.length} outlines`);
  process.exit(0);
}
const id = args.find((a) => !a.startsWith("--"));
const d = new Float32Array(fs.readFileSync(path.join(root, ".cache/pr3", `${id}-world.bin`)).buffer.slice(0)); // prettier-ignore
const N = d.length / 9;
const band = opt("band", "-9,9").split(",").map(Number);
const box = opt("box", "-9,9,-9,9").split(",").map(Number);
const n = Number(opt("n", 48));
const pts = [];
for (let i = 0; i < N; i++) {
  const [x, y, z, r, g, b, o, size, stretch] = d.subarray(i * 9, i * 9 + 9);
  if (o < 0.5 || y < band[0] || y > band[1]) continue;
  if (x < box[0] || x > box[1] || z < box[2] || z > box[3]) continue;
  pts.push({ x, y, z, r, g, b, size, stretch });
}
if (args.includes("--hist")) {
  const h = new Map();
  for (const p of pts) {
    const k = Math.floor(p.y * 50) / 50;
    h.set(k, (h.get(k) || 0) + 1);
  }
  for (const k of [...h.keys()].sort((a, b) => a - b)) console.log(k.toFixed(2), h.get(k));
}
const cx = pts.reduce((s, p) => s + p.x, 0) / pts.length;
const cz = pts.reduce((s, p) => s + p.z, 0) / pts.length;
// The outline: the 97th percentile radius in each sector.
const sectors = Array.from({ length: n }, () => []);
for (const p of pts) {
  const a = Math.atan2(p.z - cz, p.x - cx);
  sectors[((Math.floor(((a + Math.PI * 2) % (Math.PI * 2)) / ((Math.PI * 2) / n)) % n) + n) % n].push(Math.hypot(p.x - cx, p.z - cz)); // prettier-ignore
}
const radii = sectors.map((s) => {
  s.sort((a, b) => a - b);
  return s.length ? s[Math.floor(s.length * 0.97)] : 0;
});
// The lowest splats: per 0.05 cell, the 10th percentile height; then a least-squares plane.
const cells = new Map();
for (const p of pts) {
  const k = `${Math.floor(p.x / 0.05)},${Math.floor(p.z / 0.05)}`;
  if (!cells.has(k)) cells.set(k, []);
  cells.get(k).push(p);
}
const low = [];
for (const c of cells.values()) {
  if (c.length < 4) continue;
  c.sort((a, b) => a.y - b.y);
  const q = c[Math.floor(c.length * 0.1)];
  low.push([q.x, q.y, q.z]);
}
// Normal equations for y = a + b x + c z.
const S = Array.from({ length: 3 }, () => [0, 0, 0, 0]);
for (const [x, y, z] of low) {
  const v = [1, x, z];
  for (let i = 0; i < 3; i++) {
    for (let j = 0; j < 3; j++) S[i][j] += v[i] * v[j];
    S[i][3] += v[i] * y;
  }
}
for (let i = 0; i < 3; i++) {
  for (let k = i + 1; k < 3; k++) {
    const f = S[k][i] / S[i][i];
    for (let j = i; j < 4; j++) S[k][j] -= f * S[i][j];
  }
}
const plane = [0, 0, 0];
for (let i = 2; i >= 0; i--) {
  let s = S[i][3];
  for (let j = i + 1; j < 3; j++) s -= S[i][j] * plane[j];
  plane[i] = s / S[i][i];
}
const med = (k) => {
  const v = pts.map((p) => p[k]).sort((a, b) => a - b);
  return v[Math.floor(v.length / 2)];
};
// The smallest rectangle round the points (2nd to 98th percentiles along each side), for boards
// and mats: its center, its angle (of the first side, from +x toward +z) and its half sizes.
let rect = null;
for (let deg = 0; deg < 90; deg += 0.5) {
  const a = (deg * Math.PI) / 180;
  const [c, s] = [Math.cos(a), Math.sin(a)];
  const u = pts.map((p) => p.x * c + p.z * s).sort((p, q) => p - q);
  const v = pts.map((p) => -p.x * s + p.z * c).sort((p, q) => p - q);
  const q = (arr, f) => arr[Math.floor(arr.length * f)];
  const [u0, u1, v0, v1] = [q(u, 0.02), q(u, 0.98), q(v, 0.02), q(v, 0.98)];
  const area = (u1 - u0) * (v1 - v0);
  if (!rect || area < rect.area) {
    const mu = (u0 + u1) / 2;
    const mv = (v0 + v1) / 2;
    rect = { area, center: [mu * c - mv * s, mu * s + mv * c], angle: a, half: [(u1 - u0) / 2, (v1 - v0) / 2] }; // prettier-ignore
  }
}
// --top=G: the colors of the toy's top surface seen from above, on a grid of G (12-bit hex, three
// characters a cell, "000" where nothing is), for an underside that matches its top (a steak is
// seared on both sides).
let top;
if (opt("top", "")) {
  const G = Number(opt("top", ""));
  const all = [];
  for (let i = 0; i < N; i++) {
    const [x, y, z, r, g, b, o, size, stretch] = d.subarray(i * 9, i * 9 + 9);
    if (o > 0.5 && stretch < 3) all.push({ x, y, z, r, g, b });
  }
  const x0 = Math.min(...pts.map((p) => p.x)) - G;
  const z0 = Math.min(...pts.map((p) => p.z)) - G;
  const nx = Math.ceil((Math.max(...pts.map((p) => p.x)) - x0) / G) + 2;
  const nz = Math.ceil((Math.max(...pts.map((p) => p.z)) - z0) / G) + 2;
  const cells = Array.from({ length: nx * nz }, () => []);
  for (const p of all) {
    const a = Math.floor((p.x - x0) / G);
    const c = Math.floor((p.z - z0) / G);
    if (a >= 0 && c >= 0 && a < nx && c < nz) cells[c * nx + a].push(p);
  }
  const h1 = (v) => Math.round(Math.min(1, Math.max(0, v)) * 15).toString(16);
  let cols = "";
  for (const cell of cells) {
    if (!cell.length) {
      cols += "000";
      continue;
    }
    cell.sort((p, q) => q.y - p.y);
    const t = cell.slice(0, 4);
    cols += ["r", "g", "b"].map((k) => h1(t.reduce((s, p) => s + p[k], 0) / t.length)).join("");
  }
  top = { x0: +x0.toFixed(3), z0: +z0.toFixed(3), G, nx, nz, cols };
}
const hex = (v) => Math.round(Math.min(1, Math.max(0, v)) * 255).toString(16).padStart(2, "0"); // prettier-ignore
const r2 = (v) => +v.toFixed(3);
console.log(
  JSON.stringify({
    id,
    count: pts.length,
    center: [r2(cx), r2(cz)],
    plane: plane.map(r2),
    lowest: r2(Math.min(...low.map((l) => l[1]))),
    color: "#" + hex(med("r")) + hex(med("g")) + hex(med("b")),
    radii: radii.map((r) => +r.toFixed(2)),
    rect: { center: rect.center.map(r2), angle: r2(rect.angle), half: rect.half.map(r2) },
    top,
  }),
);
