// Lane Sound and light lab: fetches the visible emission lines (380 to 750
// nm, in air) of fifteen neutral atoms from NIST's Handbook of Basic Atomic
// Spectroscopic Data, "Strong Lines" tables (Sansonetti and Martin, J.
// Phys. Chem. Ref. Data 34, 1559 (2005); online as NIST SRD 108, drawn from
// the Atomic Spectra Database), and writes src/labs/nist-lines.js.
//
//   node tools/sll-nist.mjs            fetch and write
//   node tools/sll-nist.mjs --check    fetch and compare with the file
//
// Each table's air wavelengths (Å) become nm with every digit NIST gives
// kept (as a string, then a number). Only the neutral atom's lines (the
// "X I" spectrum) are kept: a lamp of the gas or vapor shows mostly those.
// The intensities are NIST's relative ones, comparable only within one
// element's table.

import { writeFileSync, readFileSync } from "node:fs";

export const ELEMENTS = [
  ["H", "Hydrogen", "hydrogen"],
  ["He", "Helium", "helium"],
  ["Li", "Lithium", "lithium"],
  ["Na", "Sodium", "sodium"],
  ["K", "Potassium", "potassium"],
  ["Ca", "Calcium", "calcium"],
  ["Sr", "Strontium", "strontium"],
  ["Ba", "Barium", "barium"],
  ["Cu", "Copper", "copper"],
  ["Zn", "Zinc", "zinc"],
  ["Cd", "Cadmium", "cadmium"],
  ["Hg", "Mercury", "mercury"],
  ["Ne", "Neon", "neon"],
  ["Ar", "Argon", "argon"],
  ["Kr", "Krypton", "krypton"],
  ["Xe", "Xenon", "xenon"],
];

const LO = 3800; // Å
const HI = 7500;
const url = (page) => `https://physics.nist.gov/PhysRefData/Handbook/Tables/${page}table2.htm`;

const text = (s) =>
  s
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&[a-z]+;/g, " ")
    .replace(/\s+/g, " ")
    .trim();

export function parseTable(html, symbol) {
  const air = html.search(/Air<br>Wavelength/i);
  if (air < 0) throw new Error(`${symbol}: no air wavelengths`);
  const out = [];
  for (const row of html.slice(air).matchAll(/<tr>(.*?)<\/tr>/gs)) {
    const cells = [...row[1].matchAll(/<td[^>]*>(.*?)<\/td>/gs)].map((m) => text(m[1]));
    if (cells.length < 3) continue;
    const [inten, wl, spec] = cells;
    if (spec !== `${symbol} I`) continue;
    const a = Number(wl);
    if (!(a >= LO && a <= HI)) continue;
    const m = /^(\d+)/.exec(inten);
    // Some rows give no number (a blend, a line seen only in absorption).
    out.push({ nm: wl, i: m ? Number(m[1]) : 0, p: /\bP\b/.test(inten) });
  }
  return out;
}

const nmOf = (aStr) => {
  // Å to nm, digit for digit (move the point one place).
  const [w, f = ""] = aStr.split(".");
  return Number(`${w.slice(0, -1)}.${w.slice(-1)}${f}`);
};

async function main() {
  const check = process.argv.includes("--check");
  const all = [];
  for (const [symbol, name, page] of ELEMENTS) {
    const r = await fetch(url(page));
    if (!r.ok) throw new Error(`${name}: HTTP ${r.status}`);
    const lines = parseTable(await r.text(), symbol).map((l) => [nmOf(l.nm), l.i, l.p ? 1 : 0]);
    lines.sort((a, b) => a[0] - b[0]);
    all.push({ symbol, name, source: url(page), lines });
    console.log(`${name}: ${lines.length} lines`);
  }
  const body = all
    .map(
      (e) =>
        `  {\n    symbol: ${JSON.stringify(e.symbol)},\n    name: ${JSON.stringify(e.name)},\n    source: ${JSON.stringify(e.source)},\n    lines: [\n${e.lines.map((l) => `      [${l.join(", ")}],`).join("\n")}\n    ],\n  },`,
    )
    .join("\n");
  const file = `// Generated by tools/sll-nist.mjs (lane Sound and light lab): do not edit.
// The visible lines (380 to 750 nm, wavelengths in air) of neutral atoms,
// from NIST's Handbook of Basic Atomic Spectroscopic Data, "Strong Lines"
// tables (Sansonetti and Martin; NIST SRD 108, from the Atomic Spectra
// Database). Each line is [nm, NIST's relative intensity (within the
// element only; 0 where NIST gives none), 1 for a persistent line].
// Fetched ${new Date().toISOString().slice(0, 10)}.

export const NIST_LINES = [
${body}
];
`;
  const dest = new URL("../src/labs/nist-lines.js", import.meta.url);
  if (check) {
    const old = readFileSync(dest, "utf8").replace(/^\/\/ Fetched.*$/m, "");
    const same = old === file.replace(/^\/\/ Fetched.*$/m, "");
    console.log(same ? "Same as NIST's tables." : "Differs from NIST's tables now.");
    process.exit(same ? 0 : 1);
  }
  writeFileSync(dest, file);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
