#!/usr/bin/env node
// Checks tools/toy-plan.json against the shelf and writes docs/TOY-PLAN.md:
// every toy's current tap action (read from its recipe), the owner's review
// notes, and the proposed effect, sound and visual fix, grouped by phase.
//
//   node tools/toy-plan.mjs          # check and write docs/TOY-PLAN.md
//   node tools/toy-plan.mjs --json   # print the merged data as JSON
//
// Fails when a shelf toy has no plan entry or an entry names no shelf toy.
// Run `npx prettier --write docs/TOY-PLAN.md` afterwards.

import fs from "node:fs";
import path from "node:path";
import { TOYS } from "../src/toys.js";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const plan = JSON.parse(fs.readFileSync(path.join(root, "tools/toy-plan.json"), "utf8")).toys;

// New effects are built in waves by shelf category (see docs/HANDOFF.md).
export const WAVES = [
  { id: "E1", title: "Scans and shapes", categories: ["scans", "shapes"] },
  { id: "E2", title: "Space, atoms and gems", categories: ["space", "atoms", "gems"] },
  { id: "E3", title: "Tiny things, anatomy and maths", categories: ["tiny", "anatomy", "maths"] },
  { id: "E4", title: "Nature and weather", categories: ["nature", "weather"] },
  { id: "E5", title: "Food", categories: ["food"] },
  {
    id: "E6",
    title: "Balls and the rest",
    categories: [
      "balls",
      "toys",
      "objects",
      "medieval",
      "animals",
      "holidays",
      "music",
      "vehicles",
      "landmarks",
    ],
  },
];
const waveOf = (category) => WAVES.find((w) => w.categories.includes(category))?.id || "E6";

const problems = [];
const rows = [];
for (const t of TOYS) {
  const p = plan[t.id];
  if (!p) {
    problems.push(`${t.id}: no entry in tools/toy-plan.json`);
    continue;
  }
  if (!["keep", "more", "new"].includes(p.v)) problems.push(`${t.id}: unknown verdict ${p.v}`);
  if (p.v !== "keep" && !p.effect) problems.push(`${t.id}: needs an effect proposal`);
  if (!p.sound) problems.push(`${t.id}: needs a sound proposal`);
  let now = "hops";
  if (t.kind === "kit") {
    const mod = await import(`../src/packs/${t.pack}.js`);
    const r = mod.RECIPES[t.id];
    if (r?.action?.label) now = `tap: ${r.action.label}`;
  }
  rows.push({
    id: t.id,
    label: t.label,
    category: t.category,
    kind: t.kind,
    now,
    ...p,
    wave: p.v === "new" ? waveOf(t.category) : null,
  });
}
for (const id of Object.keys(plan)) {
  if (!TOYS.some((t) => t.id === id))
    problems.push(`${id}: in tools/toy-plan.json but not on the shelf`);
}
if (problems.length) {
  console.error(problems.join("\n"));
  process.exit(1);
}
if (process.argv.includes("--json")) {
  process.stdout.write(JSON.stringify(rows, null, 1));
  process.exit(0);
}

const count = (f) => rows.filter(f).length;
const list = (f) =>
  rows
    .filter(f)
    .map((r) => r.label)
    .join(", ");
const out = [];
out.push(
  "# Toy plan",
  "",
  "Generated by `node tools/toy-plan.mjs` from `tools/toy-plan.json`. Do not edit this file by hand;",
  "edit the JSON and run the tool again. The owner's full review is in",
  "[reviews/2026-09-23/review.md](reviews/2026-09-23/review.md).",
  "",
  "The owner wants **every toy to have its own tap effect and its own sound**. Similar toys (the two",
  "rubber ducks, the two croissants, the two alarm clocks) must look, act and sound different.",
  "Proposals below are suggestions; the owner may change them.",
  "",
  "## Totals",
  "",
  `- ${rows.length} toys. ${count((r) => r.now !== "hops")} have a tap action today; the other ${count((r) => r.now === "hops")} only hop.`,
  `- **keep** (the owner likes the effect): ${count((r) => r.v === "keep")}.`,
  `- **more** (has an effect; make it clearer or more dramatic): ${count((r) => r.v === "more")}.`,
  `- **new** (needs its own effect): ${count((r) => r.v === "new")}.`,
  `- Visual fixes: ${count((r) => r.fix)} open, ${count((r) => r.fixed)} done. Touch or drag interaction asked for: ${count((r) => r.interactive)}.`,
  "",
  "## By phase",
  "",
  `- **C, polish.** Visual fixes still open: ${list((r) => r.fix) || "none"}. Done in C1: ${list((r) => r.fixed) || "none"}.`,
  `  Make the effect clearer or more dramatic: ${list((r) => r.v === "more" && !r.interactive)}.`,
  "- **D, effects and sound engine.** A unique sound for every toy (the Sound column below), starting",
  "  with the toys whose effect is kept.",
  ...WAVES.map(
    (w) =>
      `- **${w.id}, new effects: ${w.title.toLowerCase()}.** ${list((r) => r.wave === w.id) || "None."}`,
  ),
  `- **F, touch and drag interaction.** ${list((r) => r.interactive)}.`,
  "",
);

const categories = [...new Set(rows.map((r) => r.category))];
for (const c of categories) {
  const inCat = rows.filter((r) => r.category === c);
  out.push(`## ${c[0].toUpperCase()}${c.slice(1)} (${inCat.length})`, "");
  for (const r of inCat) {
    const tag = r.v === "new" ? `new effect (${r.wave})` : r.v;
    out.push(`- **${r.label}** (\`${r.id}\`). Now: ${r.now}. Plan: ${tag}.`);
    if (r.owner) out.push(`  - Owner: ${r.owner}`);
    if (r.fix) out.push(`  - Fix: ${r.fix}`);
    if (r.fixed) out.push(`  - Fixed: ${r.fixed}`);
    if (r.effect) out.push(`  - Effect: ${r.effect}`);
    out.push(`  - Sound: ${r.sound}`);
    if (r.interactive) out.push("  - Touch or drag interaction (phase F).");
  }
  out.push("");
}
const file = path.join(root, "docs/TOY-PLAN.md");
fs.writeFileSync(file, out.join("\n"));
console.log(`${rows.length} toys -> ${path.relative(root, file)}`);
