// Credits for the recorded samples in assets/sounds/ (the `sample` voice in
// src/voices.js), by file name: { label, title, author, source, license,
// licenseUrl }. The About tab lists the ones the current toy's sound uses;
// tools/assets.json ("soundSamples") keeps the full record of each file.

// The grand piano's notes: one pack, one credit line.
const GRAND = {
  label: "Piano",
  title: "88 piano keys, long reverb",
  author: "TEDAgame",
  source: "https://freesound.org/people/TEDAgame/packs/25405/",
  license: "CC0 1.0",
  licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
};

// Lane Sound A (September 30, 2026): CC0 recordings from Freesound and Kenney.
export const SOUND_CREDITS = {
  "grand-piano-a0.mp3": GRAND,
  "grand-piano-cs1.mp3": GRAND,
  "grand-piano-f1.mp3": GRAND,
  "grand-piano-a1.mp3": GRAND,
  "grand-piano-cs2.mp3": GRAND,
  "grand-piano-f2.mp3": GRAND,
  "grand-piano-a2.mp3": GRAND,
  "grand-piano-cs3.mp3": GRAND,
  "grand-piano-f3.mp3": GRAND,
  "grand-piano-a3.mp3": GRAND,
  "grand-piano-cs4.mp3": GRAND,
  "grand-piano-f4.mp3": GRAND,
  "grand-piano-a4.mp3": GRAND,
  "grand-piano-cs5.mp3": GRAND,
  "grand-piano-f5.mp3": GRAND,
  "grand-piano-a5.mp3": GRAND,
  "grand-piano-cs6.mp3": GRAND,
  "grand-piano-f6.mp3": GRAND,
  "grand-piano-a6.mp3": GRAND,
  "grand-piano-cs7.mp3": GRAND,
  "grand-piano-f7.mp3": GRAND,
  "grand-piano-a7.mp3": GRAND,
  "grand-piano-c8.mp3": GRAND,
  "alarm-clock-bell.mp3": {
    label: "Sound",
    title: "old alarm clock ringing",
    author: "tuberatanka",
    source: "https://freesound.org/people/tuberatanka/sounds/102435/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "asteroid-crumble.mp3": {
    label: "Sound",
    title: "Rocks.wav",
    author: "adamgryu",
    source: "https://freesound.org/people/adamgryu/sounds/336023/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "baseball-bat.mp3": {
    label: "Sound",
    title: "Bat Hit 9 FF095.aif",
    author: "martinimeniscus",
    source: "https://freesound.org/people/martinimeniscus/sounds/162886/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "beach-ball-bounce.mp3": {
    label: "Sound",
    title: "fotballPlast.wav",
    author: "blindmanonacid",
    source: "https://freesound.org/people/blindmanonacid/sounds/117111/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "bowling-ball-pins.mp3": {
    label: "Sound",
    title: "B_2 Bowling ball striking pins.wav",
    author: "Yarmonics",
    source: "https://freesound.org/people/Yarmonics/sounds/441856/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "bowling-ball-roll.mp3": {
    label: "Sound",
    title: "Bowling Ball.wav",
    author: "driftworks",
    source: "https://freesound.org/people/driftworks/sounds/128969/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "cat-statue-meow.mp3": {
    label: "Sound",
    title: "cat meow short",
    author: "skymary",
    source: "https://freesound.org/people/skymary/sounds/412017/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "comet-fire.mp3": {
    label: "Sound",
    title: "Torch.wav",
    author: "DanielVega",
    source: "https://freesound.org/people/DanielVega/sounds/479338/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "crystal-ball-ring.mp3": {
    label: "Sound",
    title: "Wine glass clink deeper.wav",
    author: "lmr9",
    source: "https://freesound.org/people/lmr9/sounds/178178/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "crystal-lattice-chain.mp3": {
    label: "Sound",
    title: "Steel chain soft drop",
    author: "ani_music",
    source: "https://freesound.org/people/ani_music/sounds/167913/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "diamond-tap.mp3": {
    label: "Sound",
    title: "Glass Tap.wav",
    author: "Unicornaphobist",
    source: "https://freesound.org/people/Unicornaphobist/sounds/262958/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "dna-zipper.mp3": {
    label: "Sound",
    title: "Zipper Unzip 3 (Slow) .wav",
    author: "RutgerMuller",
    source: "https://freesound.org/people/RutgerMuller/sounds/51176/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "heart-beat.mp3": {
    label: "Sound",
    title: "Human Heartbeat (60 BPM)",
    author: "FenrirFangs",
    source: "https://freesound.org/people/FenrirFangs/sounds/213181/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "horse-statue-whinny.mp3": {
    label: "Sound",
    title: "Renill de cavall / Horse Neigh",
    author: "Salsero_classic",
    source: "https://freesound.org/people/Salsero_classic/sounds/826753/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "lantern-blow.mp3": {
    label: "Sound",
    title: "blowing out candle.wav",
    author: "Reitanna",
    source: "https://freesound.org/people/Reitanna/sounds/242867/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "lantern-match.mp3": {
    label: "Sound",
    title: "Match Lighting Candle",
    author: "devilqube",
    source: "https://freesound.org/people/devilqube/sounds/370362/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "lungs-breath.mp3": {
    label: "Sound",
    title: "Male breathing",
    author: "zogmachine",
    source: "https://freesound.org/people/zogmachine/sounds/202606/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "marble-roll.mp3": {
    label: "Sound",
    title: "Marble (single) rolling on wooden floor.wav",
    author: "LiezelDippenaar",
    source: "https://freesound.org/people/LiezelDippenaar/sounds/707545/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "meteor-boom.mp3": {
    label: "Sound",
    title: "Muffled Distant Explosion",
    author: "NenadSimic",
    source: "https://freesound.org/people/NenadSimic/sounds/149966/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "meteor-fire.mp3": {
    label: "Sound",
    title: "Waving Torch.wav",
    author: "spookymodem",
    source: "https://freesound.org/people/spookymodem/sounds/249809/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "neuron-arc.mp3": {
    label: "Sound",
    title: "highvoltagearc.wav",
    author: "Sclolex",
    source: "https://freesound.org/people/Sclolex/sounds/210878/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "pool-ball-cue.mp3": {
    label: "Sound",
    title: "pool_break.wav",
    author: "reg7783",
    source: "https://freesound.org/people/reg7783/sounds/204187/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "protein-velcro.mp3": {
    label: "Sound",
    title: "Velcro",
    author: "paulocorona",
    source: "https://freesound.org/people/paulocorona/sounds/334991/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "raspberry-land-1.mp3": {
    label: "Sound",
    title: "Impact Sounds (impactSoft_medium_000.ogg)",
    author: "Kenney",
    source: "https://kenney.nl/assets/impact-sounds",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "raspberry-land-2.mp3": {
    label: "Sound",
    title: "Impact Sounds (impactSoft_medium_002.ogg)",
    author: "Kenney",
    source: "https://kenney.nl/assets/impact-sounds",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "raspberry-squish.mp3": {
    label: "Sound",
    title: "Squish impact",
    author: "Bertsz",
    source: "https://freesound.org/people/Bertsz/sounds/500912/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "star-cookie-crumble.mp3": {
    label: "Sound",
    title: "Crisp Crunch.m4a",
    author: "Yin_Yang_Jake007",
    source: "https://freesound.org/people/Yin_Yang_Jake007/sounds/443469/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "star-cookie-snap.mp3": {
    label: "Sound",
    title: "Crisp Crunch.m4a",
    author: "Yin_Yang_Jake007",
    source: "https://freesound.org/people/Yin_Yang_Jake007/sounds/443469/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "supernova-boom.mp3": {
    label: "Sound",
    title: "Deep Boom",
    author: "Za-Games",
    source: "https://freesound.org/people/Za-Games/sounds/539968/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "tennis-ball-bounce.mp3": {
    label: "Sound",
    title: "bola de tenis caindo.wav",
    author: "Negraovictor",
    source: "https://freesound.org/people/Negraovictor/sounds/394355/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "tennis-ball-slam.mp3": {
    label: "Sound",
    title: "ball_hit_ground.wav",
    author: "Kyanite_",
    source: "https://freesound.org/people/Kyanite_/sounds/432912/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "tin-can-spin.mp3": {
    label: "Sound",
    title: "Spinning Coin",
    author: "CassieTee",
    source: "https://freesound.org/people/CassieTee/sounds/209462/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "vintage-camera-flash.mp3": {
    label: "Sound",
    title: "Vintage Camera Flash Powder and Shutter",
    author: "Werra",
    source: "https://freesound.org/people/Werra/sounds/232130/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "wooden-elephant-trumpet.mp3": {
    label: "Sound",
    title: "Elephant Trumpets Growls.flac",
    author: "D.jones",
    source: "https://freesound.org/people/D.jones/sounds/527845/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
};
