// Credits for the recorded samples in assets/sounds/ (the `sample` voice in
// src/voices.js), by file name: { label, title, author, source, license,
// licenseUrl }. The About tab lists the ones the current toy's sound uses;
// tools/assets.json ("soundSamples") keeps the full record of each file.

// The grand piano's notes: one pack, one credit line.
const GRAND = {
  label: "Piano",
  title: "88 piano keys, long reverb",
  author: "TEDAgame",
  source: "https://freesound.org/people/TEDAgame/packs/25405/",
  license: "CC0 1.0",
  licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
};

// Lane Sound A (September 30, 2026): CC0 recordings from Freesound and Kenney.
export const SOUND_CREDITS = {
  "grand-piano-a0.mp3": GRAND,
  "grand-piano-cs1.mp3": GRAND,
  "grand-piano-f1.mp3": GRAND,
  "grand-piano-a1.mp3": GRAND,
  "grand-piano-cs2.mp3": GRAND,
  "grand-piano-f2.mp3": GRAND,
  "grand-piano-a2.mp3": GRAND,
  "grand-piano-cs3.mp3": GRAND,
  "grand-piano-f3.mp3": GRAND,
  "grand-piano-a3.mp3": GRAND,
  "grand-piano-cs4.mp3": GRAND,
  "grand-piano-f4.mp3": GRAND,
  "grand-piano-a4.mp3": GRAND,
  "grand-piano-cs5.mp3": GRAND,
  "grand-piano-f5.mp3": GRAND,
  "grand-piano-a5.mp3": GRAND,
  "grand-piano-cs6.mp3": GRAND,
  "grand-piano-f6.mp3": GRAND,
  "grand-piano-a6.mp3": GRAND,
  "grand-piano-cs7.mp3": GRAND,
  "grand-piano-f7.mp3": GRAND,
  "grand-piano-a7.mp3": GRAND,
  "grand-piano-c8.mp3": GRAND,
  "alarm-clock-bell.mp3": {
    label: "Sound",
    title: "old alarm clock ringing",
    author: "tuberatanka",
    source: "https://freesound.org/people/tuberatanka/sounds/102435/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "asteroid-crumble.mp3": {
    label: "Sound",
    title: "Rocks.wav",
    author: "adamgryu",
    source: "https://freesound.org/people/adamgryu/sounds/336023/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "baseball-bat.mp3": {
    label: "Sound",
    title: "Bat Hit 9 FF095.aif",
    author: "martinimeniscus",
    source: "https://freesound.org/people/martinimeniscus/sounds/162886/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "beach-ball-bounce.mp3": {
    label: "Sound",
    title: "fotballPlast.wav",
    author: "blindmanonacid",
    source: "https://freesound.org/people/blindmanonacid/sounds/117111/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "bowling-ball-pins.mp3": {
    label: "Sound",
    title: "B_2 Bowling ball striking pins.wav",
    author: "Yarmonics",
    source: "https://freesound.org/people/Yarmonics/sounds/441856/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "bowling-ball-roll.mp3": {
    label: "Sound",
    title: "Bowling Ball.wav",
    author: "driftworks",
    source: "https://freesound.org/people/driftworks/sounds/128969/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "cat-statue-meow.mp3": {
    label: "Sound",
    title: "cat meow short",
    author: "skymary",
    source: "https://freesound.org/people/skymary/sounds/412017/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "comet-fire.mp3": {
    label: "Sound",
    title: "Torch.wav",
    author: "DanielVega",
    source: "https://freesound.org/people/DanielVega/sounds/479338/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "crystal-ball-ring.mp3": {
    label: "Sound",
    title: "Wine glass clink deeper.wav",
    author: "lmr9",
    source: "https://freesound.org/people/lmr9/sounds/178178/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "crystal-lattice-chain.mp3": {
    label: "Sound",
    title: "Steel chain soft drop",
    author: "ani_music",
    source: "https://freesound.org/people/ani_music/sounds/167913/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "diamond-tap.mp3": {
    label: "Sound",
    title: "Glass Tap.wav",
    author: "Unicornaphobist",
    source: "https://freesound.org/people/Unicornaphobist/sounds/262958/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "dna-zipper.mp3": {
    label: "Sound",
    title: "Zipper Unzip 3 (Slow) .wav",
    author: "RutgerMuller",
    source: "https://freesound.org/people/RutgerMuller/sounds/51176/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "heart-beat.mp3": {
    label: "Sound",
    title: "Human Heartbeat (60 BPM)",
    author: "FenrirFangs",
    source: "https://freesound.org/people/FenrirFangs/sounds/213181/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "horse-statue-whinny.mp3": {
    label: "Sound",
    title: "Renill de cavall / Horse Neigh",
    author: "Salsero_classic",
    source: "https://freesound.org/people/Salsero_classic/sounds/826753/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "lantern-blow.mp3": {
    label: "Sound",
    title: "blowing out candle.wav",
    author: "Reitanna",
    source: "https://freesound.org/people/Reitanna/sounds/242867/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "lantern-match.mp3": {
    label: "Sound",
    title: "Match Lighting Candle",
    author: "devilqube",
    source: "https://freesound.org/people/devilqube/sounds/370362/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "lungs-breath.mp3": {
    label: "Sound",
    title: "Male breathing",
    author: "zogmachine",
    source: "https://freesound.org/people/zogmachine/sounds/202606/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "marble-roll.mp3": {
    label: "Sound",
    title: "Marble (single) rolling on wooden floor.wav",
    author: "LiezelDippenaar",
    source: "https://freesound.org/people/LiezelDippenaar/sounds/707545/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "meteor-boom.mp3": {
    label: "Sound",
    title: "Muffled Distant Explosion",
    author: "NenadSimic",
    source: "https://freesound.org/people/NenadSimic/sounds/149966/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "meteor-fire.mp3": {
    label: "Sound",
    title: "Waving Torch.wav",
    author: "spookymodem",
    source: "https://freesound.org/people/spookymodem/sounds/249809/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "neuron-arc.mp3": {
    label: "Sound",
    title: "highvoltagearc.wav",
    author: "Sclolex",
    source: "https://freesound.org/people/Sclolex/sounds/210878/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "pool-ball-cue.mp3": {
    label: "Sound",
    title: "pool_break.wav",
    author: "reg7783",
    source: "https://freesound.org/people/reg7783/sounds/204187/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "protein-velcro.mp3": {
    label: "Sound",
    title: "Velcro",
    author: "paulocorona",
    source: "https://freesound.org/people/paulocorona/sounds/334991/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "raspberry-land-1.mp3": {
    label: "Sound",
    title: "Impact Sounds (impactSoft_medium_000.ogg)",
    author: "Kenney",
    source: "https://kenney.nl/assets/impact-sounds",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "raspberry-land-2.mp3": {
    label: "Sound",
    title: "Impact Sounds (impactSoft_medium_002.ogg)",
    author: "Kenney",
    source: "https://kenney.nl/assets/impact-sounds",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "raspberry-squish.mp3": {
    label: "Sound",
    title: "Squish impact",
    author: "Bertsz",
    source: "https://freesound.org/people/Bertsz/sounds/500912/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "star-cookie-crumble.mp3": {
    label: "Sound",
    title: "Crisp Crunch.m4a",
    author: "Yin_Yang_Jake007",
    source: "https://freesound.org/people/Yin_Yang_Jake007/sounds/443469/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "star-cookie-snap.mp3": {
    label: "Sound",
    title: "Crisp Crunch.m4a",
    author: "Yin_Yang_Jake007",
    source: "https://freesound.org/people/Yin_Yang_Jake007/sounds/443469/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "supernova-boom.mp3": {
    label: "Sound",
    title: "Deep Boom",
    author: "Za-Games",
    source: "https://freesound.org/people/Za-Games/sounds/539968/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "tennis-ball-bounce.mp3": {
    label: "Sound",
    title: "bola de tenis caindo.wav",
    author: "Negraovictor",
    source: "https://freesound.org/people/Negraovictor/sounds/394355/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "tennis-ball-slam.mp3": {
    label: "Sound",
    title: "ball_hit_ground.wav",
    author: "Kyanite_",
    source: "https://freesound.org/people/Kyanite_/sounds/432912/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "tin-can-spin.mp3": {
    label: "Sound",
    title: "Spinning Coin",
    author: "CassieTee",
    source: "https://freesound.org/people/CassieTee/sounds/209462/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "vintage-camera-flash.mp3": {
    label: "Sound",
    title: "Vintage Camera Flash Powder and Shutter",
    author: "Werra",
    source: "https://freesound.org/people/Werra/sounds/232130/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "wooden-elephant-trumpet.mp3": {
    label: "Sound",
    title: "Elephant Trumpets Growls.flac",
    author: "D.jones",
    source: "https://freesound.org/people/D.jones/sounds/527845/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
};

// Lane Sound B (September 30, 2026): CC0 recordings from Freesound and Kenney for
// the nature, weather, food, toys, Open me, medieval, animals, math, holidays,
// vehicles and landmarks shelves.
Object.assign(SOUND_CREDITS, {
  "puzzle-cube-turn.mp3": {
    label: "Sound",
    title: "Cube Turn - 9 (a puzzle cube turning)",
    author: "SpaceJoe",
    source: "https://freesound.org/s/486585/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "balloon-dog-pop.mp3": {
    label: "Sound",
    title: "Balloon-Burst-07.wav",
    author: "Gniffelbaf",
    source: "https://freesound.org/s/82121/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "book-page.mp3": {
    label: "Sound",
    title: "Book Turn Page 2.wav",
    author: "esperri",
    source: "https://freesound.org/s/119127/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "apple-bite.mp3": {
    label: "Sound",
    title: "Bite (Apple)",
    author: "wadaltmon",
    source: "https://freesound.org/s/275015/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "popcorn-popping.mp3": {
    label: "Sound",
    title: "popcorn.wav",
    author: "Mike888",
    source: "https://freesound.org/s/488722/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "taco-crack.mp3": {
    label: "Sound",
    title: "chips crunch sound",
    author: "TomatoHater",
    source: "https://freesound.org/s/705360/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "fireworks-burst.mp3": {
    label: "Sound",
    title: "Firework Explosion 3",
    author: "a deleted Freesound account (deleted_user_3544904)",
    source: "https://freesound.org/s/212683/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "colosseum-crowd.mp3": {
    label: "Sound",
    title: "cheering and clapping crowd 1",
    author: "AlaskaRobotics",
    source: "https://freesound.org/s/221568/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "colosseum-hooves.mp3": {
    label: "Sound",
    title: "Horse and Carriage.mp3",
    author: "maadmacs",
    source: "https://freesound.org/s/388391/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "steam-train-chug.mp3": {
    label: "Sound",
    title: "Steam Train In Motion 1.wav",
    author: "lolamadeus",
    source: "https://freesound.org/s/179349/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "sports-car-rev.mp3": {
    label: "Sound",
    title: "Car Engine Revving.WAV",
    author: "DigPro120",
    source: "https://freesound.org/s/558844/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "tractor-engine.mp3": {
    label: "Sound",
    title: "Tractor whirring",
    author: "vonis22",
    source: "https://freesound.org/s/339167/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "helicopter-rotor.mp3": {
    label: "Sound",
    title: "Helicopter.wav",
    author: "Mike_Leister",
    source: "https://freesound.org/s/488089/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "propeller-plane-engine.mp3": {
    label: "Sound",
    title: "Aeroplane Passing Close.wav",
    author: "paulprit",
    source: "https://freesound.org/s/507446/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "bow-and-target-release.mp3": {
    label: "Sound",
    title: "Bow Release (Bow and Arrow) 3",
    author: "Ali_6868",
    source: "https://freesound.org/s/384918/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "owl-hoot.mp3": {
    label: "Sound",
    title: "Owl Hoot",
    author: "Breviceps",
    source: "https://freesound.org/s/465697/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "frog-croak.mp3": {
    label: "Sound",
    title: "Frog croaking sound effect",
    author: "betterchinese",
    source: "https://freesound.org/s/354132/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "frog-fly.mp3": {
    label: "Sound",
    title: "Fly_Buzzing_Edited.wav",
    author: "AmberdeMeillon",
    source: "https://freesound.org/s/443059/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "bonsai-snip.mp3": {
    label: "Sound",
    title: "scissors cut.wav",
    author: "mywhats",
    source: "https://freesound.org/s/175522/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "oak-leaves.mp3": {
    label: "Sound",
    title: "FallingLeaves",
    author: "falcospizaetus",
    source: "https://freesound.org/s/489911/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "rocks-pebbles.mp3": {
    label: "Sound",
    title: "Slow Pebble Tumble.wav",
    author: "bbrocer",
    source: "https://freesound.org/s/398698/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "iceberg-crack.mp3": {
    label: "Sound",
    title: "Ice Crack 1",
    author: "j_p_higgins",
    source: "https://freesound.org/s/262635/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "klein-bottle-slosh.mp3": {
    label: "Sound",
    title: "Bottle Slosh 2",
    author: "alegemaate",
    source: "https://freesound.org/s/667273/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "spinning-top-spin.mp3": {
    label: "Sound",
    title: "Metallic Spinning Top (Dry Sound).wav",
    author: "Uzbazur",
    source: "https://freesound.org/s/334970/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "spring-toy-boing.mp3": {
    label: "Sound",
    title: "battery compartment spring 01.wav",
    author: "denalwa",
    source: "https://freesound.org/s/472478/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "chess-set-move.mp3": {
    label: "Sound",
    title: "Piece Placement.mp3",
    author: "el_boss",
    source: "https://freesound.org/s/546119/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "robot-wind.mp3": {
    label: "Sound",
    title: "Wind-up sound",
    author: "Breviceps",
    source: "https://freesound.org/s/445966/",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  "dice-throw.mp3": {
    label: "Sound",
    title: "Casino Audio 1.1: dice-throw-1.ogg and dice-throw-3.ogg",
    author: "Kenney (kenney.nl)",
    source: "https://kenney.nl/assets/casino-audio",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
});
