// The toy shelf: built-in toys. Captured toys are SOG files under
// assets/toys/<id>/ (prepared with tools/prepare-assets.mjs, credits in
// CREDITS.md); procedural toys are generator presets built in the browser.
//
// This catalogue is metadata only (ids, labels, categories, search words) so
// it stays small as the shelf grows; toy code that needs more than a
// generator preset lives in per-pack modules that load when a toy is picked.

// Shelf categories, in shelf order. A category only shows once it has toys.
export const CATEGORIES = [
  { id: "scans", label: "Scans" },
  { id: "shapes", label: "Shapes" },
  { id: "balls", label: "Balls" },
  { id: "space", label: "Space" },
  { id: "tiny", label: "Tiny world" },
  { id: "atoms", label: "Atoms" },
  { id: "gems", label: "Gems" },
  { id: "anatomy", label: "Body" },
  { id: "nature", label: "Nature" },
  { id: "weather", label: "Weather & fire" },
  { id: "food", label: "Food" },
  { id: "toys", label: "Toys" },
  { id: "objects", label: "Open me" },
  { id: "medieval", label: "Medieval" },
  { id: "animals", label: "Animals" },
  { id: "maths", label: "Maths" },
  { id: "holidays", label: "Holidays" },
  { id: "music", label: "Music" },
  { id: "vehicles", label: "Vehicles" },
  { id: "landmarks", label: "Landmarks" },
];

export const TOYS = [
  {
    id: "cactus",
    label: "Cactus",
    category: "scans",
    tags: "plant succulent pot captured photo real",
    kind: "captured",
    url: "assets/toys/cactus/cactus.sog",
    urlWeak: "assets/toys/cactus/cactus-lite.sog",
    credit: {
      title: "Cactus (3DGS sample data)",
      author: "steam studio / 3D SCAN STUDIO iris",
      source: "https://note.com/steam_studio/n/ne9736d94f162",
      license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      changes: "Converted to SOG, spherical harmonics removed, recentred, scaled and cropped.",
    },
  },
  {
    id: "strawberry",
    label: "Strawberry",
    category: "scans",
    tags: "fruit food berry captured photo real",
    kind: "captured",
    url: "assets/toys/strawberry/strawberry.sog",
    urlWeak: "assets/toys/strawberry/strawberry-lite.sog",
    camera: { yaw: 0.25, pitch: 0.3, roll: 0, distance: 5.6 },
    credit: {
      title: "Strawberry",
      author: "Dany Bittel",
      source: "https://superspl.at/scene/84df8849",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes: "Converted, decimated, spherical harmonics removed, recentred and scaled.",
    },
  },
  {
    id: "cookie",
    label: "Heart cookie",
    category: "scans",
    tags: "food biscuit heart sweet captured photo real",
    kind: "captured",
    url: "assets/toys/cookie/cookie.sog",
    urlWeak: "assets/toys/cookie/cookie-lite.sog",
    credit: {
      title: "Heart Cookie",
      author: "Dany Bittel",
      source: "https://superspl.at/scene/bd964899",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes: "Converted, spherical harmonics removed, recentred and scaled.",
    },
  },
  {
    id: "bee",
    label: "Honeybee",
    category: "scans",
    tags: "insect animal bug honeybee captured photo real",
    kind: "captured",
    url: "assets/toys/bee/bee.sog",
    urlWeak: "assets/toys/bee/bee-lite.sog",
    credit: {
      title: "Japanese Bee",
      author: "YUMA Co., Ltd.",
      source: "https://superspl.at/scene/ae58ed2c",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes: "Converted, decimated, spherical harmonics removed, recentred and scaled.",
    },
  },
  {
    id: "blob",
    label: "Jelly blob",
    category: "shapes",
    tags: "jelly noise candy generated",
    kind: "procedural",
    generator: {
      shape: "blob",
      palette: "candy",
      seed: 7,
      sizeJitter: 0.35,
      roughness: 0.25,
      colorNoise: 0.2,
    },
  },
  {
    id: "donut",
    label: "Donut",
    category: "shapes",
    tags: "doughnut torus food sprinkles frosting generated",
    kind: "procedural",
    generator: {
      shape: "torus",
      palette: "frosting",
      seed: 5,
      sizeJitter: 0.3,
      roughness: 0.2,
      colorNoise: 0.3,
    },
    camera: { yaw: 0.4, pitch: 0.62, roll: 0, distance: 5 },
  },
  {
    id: "knot",
    label: "Neon knot",
    category: "shapes",
    tags: "trefoil neon maths generated",
    kind: "procedural",
    generator: {
      shape: "knot",
      palette: "neon",
      seed: 11,
      sizeJitter: 0.3,
      roughness: 0.15,
      colorNoise: 0.15,
    },
  },
  {
    id: "planet",
    label: "Tiny planet",
    category: "shapes",
    tags: "earth world globe space generated v1",
    kind: "procedural",
    note: "A tribute to Splashery v1",
    generator: {
      shape: "sphere",
      palette: "planet",
      seed: 3,
      sizeJitter: 0.3,
      roughness: 0.2,
      colorNoise: 0.25,
    },
  },
  // Kit toys: recipes in src/packs/<pack>.js, built in the browser.
  {
    id: "basketball",
    label: "Basketball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball hoops court orange",
  },
  {
    id: "soccer-ball",
    label: "Soccer ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball football association pentagon hexagon",
  },
  {
    id: "american-football",
    label: "American football",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball gridiron laces pigskin",
    camera: { yaw: 0.35, pitch: 0.62, roll: 0, distance: 5 },
  },
  {
    id: "tennis-ball",
    label: "Tennis ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball felt fuzzy yellow racket",
  },
  {
    id: "baseball",
    label: "Baseball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball stitches bat diamond",
  },
  {
    id: "softball",
    label: "Softball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball stitches yellow",
  },
  {
    id: "beach-ball",
    label: "Beach ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball inflatable summer stripes",
  },
  {
    id: "golf-ball",
    label: "Golf ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball dimples tee",
  },
  {
    id: "rugby-ball",
    label: "Rugby ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball oval try",
  },
  {
    id: "volleyball",
    label: "Volleyball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball net beach panels",
  },
  {
    id: "water-polo-ball",
    label: "Water polo ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball pool swim grip",
  },
  {
    id: "ping-pong-ball",
    label: "Ping-pong ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball table tennis small",
  },
  {
    id: "cricket-ball",
    label: "Cricket ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball leather seam red",
  },
  {
    id: "bowling-ball",
    label: "Bowling ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball pins lane holes",
  },
  {
    id: "pool-ball",
    label: "Pool ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball billiards snooker cue eight number",
  },
  {
    id: "pickleball",
    label: "Pickleball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball paddle holes wiffle",
  },
  {
    id: "dodgeball",
    label: "Dodgeball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball playground rubber",
  },
  {
    id: "medicine-ball",
    label: "Medicine ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball gym workout heavy",
  },
  {
    id: "lacrosse-ball",
    label: "Lacrosse ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball rubber stick",
  },
  {
    id: "squash-ball",
    label: "Squash ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball racquet dots",
  },
  {
    id: "bouncy-ball",
    label: "Bouncy ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball super rubber swirl",
  },
  {
    id: "marble",
    label: "Marble",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball glass cats eye",
  },
  {
    id: "hockey-puck",
    label: "Hockey puck",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball ice rink",
  },
  {
    id: "shuttlecock",
    label: "Shuttlecock",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball badminton birdie feathers",
  },
  {
    id: "flying-disc",
    label: "Flying disc",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball throw frisbee catch",
  },
  {
    id: "heart",
    label: "Beating heart",
    category: "anatomy",
    kind: "kit",
    pack: "anatomy",
    tags: "organ body cardio pulse love valentine",
  },
  {
    id: "campfire",
    label: "Campfire",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "fire flame camping logs embers sparks",
    camera: { yaw: 0.5, pitch: 0.38, roll: 0, distance: 5 },
  },
  {
    id: "chest",
    label: "Treasure chest",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "pirate gold coins gems box lid open close",
    camera: { yaw: 0.45, pitch: 0.42, roll: 0, distance: 5.4 },
  },
  // ---- Pack: space ----
  {
    id: "sun",
    label: "Sun",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "star solar corona prominence sunspot hot yellow",
  },
  {
    id: "solar-system",
    label: "Solar system",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "orrery planets orbits sun model",
    camera: { yaw: 0.55, pitch: 0.72, roll: 0, distance: 3.7 },
  },
  {
    id: "mercury",
    label: "Mercury",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planet craters grey rocky small solar system",
  },
  {
    id: "venus",
    label: "Venus",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planet clouds yellow hot solar system",
  },
  {
    id: "earth",
    label: "Earth",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planet world globe ocean continents clouds home blue",
  },
  {
    id: "moon",
    label: "Moon",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "lunar craters maria grey satellite",
  },
  {
    id: "mars",
    label: "Mars",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planet red rust polar cap solar system",
  },
  {
    id: "jupiter",
    label: "Jupiter",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planet gas giant bands great red spot storm",
  },
  {
    id: "saturn",
    label: "Saturn",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planet rings gas giant bands",
    camera: { yaw: 0.55, pitch: 0.28, roll: 0, distance: 4.3 },
  },
  {
    id: "uranus",
    label: "Uranus",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planet ice giant cyan rings tilted",
    camera: { yaw: 0.55, pitch: 0.28, roll: 0, distance: 4.5 },
  },
  {
    id: "neptune",
    label: "Neptune",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planet ice giant blue dark spot wind",
  },
  {
    id: "aurora-planet",
    label: "Aurora world",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planet night aurora northern lights city lights earth",
  },
  {
    id: "asteroid",
    label: "Asteroid",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "rock space potato craters tumble",
  },
  {
    id: "comet",
    label: "Comet",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "ice tail dust coma nucleus",
  },
  {
    id: "meteor",
    label: "Meteor",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "shooting star fireball rock fire trail falling",
  },
  {
    id: "star",
    label: "Star",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "sun red dwarf blue giant white dwarf twinkle",
  },
  {
    id: "pulsar",
    label: "Pulsar",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "neutron star beams lighthouse spin magnetic",
  },
  {
    id: "black-hole",
    label: "Black hole",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "accretion disk event horizon gravity lensing",
    camera: { yaw: 0.55, pitch: 0.16, roll: 0, distance: 4.4 },
  },
  {
    id: "star-cluster",
    label: "Star cluster",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "globular cluster stars twinkle",
  },
  {
    id: "planetary-nebula",
    label: "Ring nebula",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planetary nebula shell gas dying star ring",
    camera: { yaw: 0.35, pitch: 0.3, roll: 0, distance: 4.6 },
  },
  {
    id: "nebula",
    label: "Nebula",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "gas cloud pillars stars emission colourful",
    camera: { yaw: 0, pitch: 0.06, roll: 0, distance: 4.4 },
  },
  {
    id: "supernova",
    label: "Supernova",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "explosion star remnant debris blast",
  },
  {
    id: "spiral-galaxy",
    label: "Spiral galaxy",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "milky way andromeda stars arms barred",
    camera: { yaw: 0.55, pitch: 0.9, roll: 0, distance: 3.5 },
  },

  // ---- Pack: tiny ----
  // (entries for src/packs/tiny.js go here)
  {
    id: "virus",
    label: "Virus",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "microbe germ capsid spikes icosahedron microscope biology",
  },
  {
    id: "bacteriophage",
    label: "Bacteriophage",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "phage virus microbe tail fibres lander inject dna microscope biology",
    camera: { yaw: 0.55, pitch: 0.2, roll: 0, distance: 4.4 },
  },
  {
    id: "bacterium",
    label: "Bacterium",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "microbe germ bacteria rod flagella pili swim microscope biology",
  },
  {
    id: "red-blood-cell",
    label: "Red blood cell",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "cell blood erythrocyte disc body microscope biology",
  },
  {
    id: "neuron",
    label: "Neuron",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "nerve cell brain axon dendrite myelin synapse signal microscope biology",
    camera: { yaw: 0.55, pitch: 0.28, roll: 0, distance: 4.5 },
  },
  {
    id: "astrocyte",
    label: "Astrocyte",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "glia glial star cell brain nerve end feet microscope biology",
  },
  {
    id: "animal-cell",
    label: "Animal cell",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "cell nucleus mitochondria golgi organelles membrane microscope biology",
  },
  {
    id: "dna",
    label: "DNA",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "double helix gene genome base pairs unzip molecule biology",
    camera: { yaw: 0.55, pitch: 0.28, roll: 0, distance: 4.5 },
  },
  {
    id: "white-blood-cell",
    label: "White blood cell",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "cell blood immune leukocyte neutrophil granules body microscope biology",
  },
  {
    id: "microglia",
    label: "Microglia",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "glia glial cell brain immune branches microscope biology",
  },
  {
    id: "diatom",
    label: "Diatom",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "algae plankton glass silica shell pores ocean microscope biology",
    camera: { yaw: 0.55, pitch: 0.45, roll: 0, distance: 5 },
  },
  {
    id: "tardigrade",
    label: "Tardigrade",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "water bear moss piglet animal legs claws cute microscope biology",
  },
  {
    id: "pollen",
    label: "Pollen grain",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "plant flower spiky allergy sunflower pine lily microscope biology",
  },
  {
    id: "snowflake",
    label: "Snowflake",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "snow ice crystal winter frost six hexagon weather",
    camera: { yaw: 0.3, pitch: 0.15, roll: 0, distance: 5 },
  },
  {
    id: "chromosome",
    label: "Chromosome",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "dna gene chromatid centromere genetics cell biology",
  },
  {
    id: "mitochondrion",
    label: "Mitochondrion",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "mitochondria cell powerhouse energy cristae organelle biology",
  },
  {
    id: "paramecium",
    label: "Paramecium",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "protist ciliate cilia pond water swim microscope biology",
  },
  {
    id: "amoeba",
    label: "Amoeba",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "protist blob pseudopod pond water microscope biology",
    camera: { yaw: 0.55, pitch: 0.5, roll: 0, distance: 5 },
  },

  // ---- Pack: atoms ----
  // (entries for src/packs/atoms.js go here)
  {
    id: "orbital",
    label: "Electron orbital",
    category: "atoms",
    kind: "kit",
    pack: "atoms",
    tags: "atom electron cloud quantum wave function hydrogen chemistry physics",
  },
  {
    id: "atom",
    label: "Atom",
    category: "atoms",
    kind: "kit",
    pack: "atoms",
    tags: "bohr element nucleus proton neutron electron shell periodic table chemistry physics",
  },
  {
    id: "molecule",
    label: "Molecule",
    category: "atoms",
    kind: "kit",
    pack: "atoms",
    tags: "ball stick water caffeine benzene methane ethanol buckyball chemistry",
  },
  {
    id: "crystal-lattice",
    label: "Crystal lattice",
    category: "atoms",
    kind: "kit",
    pack: "atoms",
    tags: "salt diamond graphite ice crystal structure atoms chemistry",
  },

  // ---- Pack: gems ----
  // (entries for src/packs/gems.js go here)
  {
    id: "diamond",
    label: "Diamond",
    category: "gems",
    kind: "kit",
    pack: "gems",
    tags: "gem jewel brilliant cut sparkle stone mineral",
  },
  {
    id: "ruby",
    label: "Ruby",
    category: "gems",
    kind: "kit",
    pack: "gems",
    tags: "gem jewel red oval cut stone mineral",
  },
  {
    id: "emerald",
    label: "Emerald",
    category: "gems",
    kind: "kit",
    pack: "gems",
    tags: "gem jewel green step cut stone mineral",
  },
  {
    id: "amethyst-geode",
    label: "Amethyst geode",
    category: "gems",
    kind: "kit",
    pack: "gems",
    tags: "gem crystal purple rock cave open quartz mineral",
  },
  {
    id: "sapphire",
    label: "Sapphire",
    category: "gems",
    kind: "kit",
    pack: "gems",
    tags: "gem jewel blue cushion cut stone mineral",
  },
  {
    id: "quartz-cluster",
    label: "Quartz cluster",
    category: "gems",
    kind: "kit",
    pack: "gems",
    tags: "crystal points rock clear mineral",
  },
  {
    id: "opal",
    label: "Opal",
    category: "gems",
    kind: "kit",
    pack: "gems",
    tags: "gem jewel rainbow play of colour cabochon stone mineral",
  },
  {
    id: "pearl",
    label: "Pearl",
    category: "gems",
    kind: "kit",
    pack: "gems",
    tags: "gem jewel oyster shell lustre sea open",
  },
  {
    id: "crystal-ball",
    label: "Crystal ball",
    category: "gems",
    kind: "kit",
    pack: "gems",
    tags: "glass orb magic mist fortune stand swirl",
  },

  // ---- Pack: anatomy ----
  // (entries for src/packs/anatomy.js go here)
  {
    id: "brain",
    label: "Brain",
    category: "anatomy",
    kind: "kit",
    pack: "anatomy",
    tags: "organ body mind think lobes cerebrum cerebellum neuron nerve",
  },
  {
    id: "eye",
    label: "Eye",
    category: "anatomy",
    kind: "kit",
    pack: "anatomy",
    tags: "organ body eyeball iris pupil see vision look",
  },
  {
    id: "lungs",
    label: "Lungs",
    category: "anatomy",
    kind: "kit",
    pack: "anatomy",
    tags: "organ body breathe air trachea bronchi respiration",
    camera: { yaw: 0.35, pitch: 0.2, roll: 0, distance: 5 },
  },
  {
    id: "tooth",
    label: "Tooth",
    category: "anatomy",
    kind: "kit",
    pack: "anatomy",
    tags: "molar teeth dentist enamel root body mouth",
  },
  {
    id: "kidney",
    label: "Kidney",
    category: "anatomy",
    kind: "kit",
    pack: "anatomy",
    tags: "organ body bean urine filter renal",
  },

  // ---- Pack: nature ----
  // (entries for src/packs/nature.js go here)
  {
    id: "oak",
    label: "Oak tree",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "tree plant leaves branches forest acorn season autumn winter",
    camera: { yaw: 0.5, pitch: 0.22, roll: 0, distance: 4.2 },
  },
  {
    id: "pine",
    label: "Pine tree",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "tree plant conifer evergreen fir spruce forest needles snow christmas",
    camera: { yaw: 0.5, pitch: 0.22, roll: 0, distance: 4.2 },
  },
  {
    id: "palm",
    label: "Palm tree",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "tree plant tropical beach island coconut fronds",
    camera: { yaw: 0.5, pitch: 0.22, roll: 0, distance: 4.2 },
  },
  {
    id: "cherry-blossom",
    label: "Cherry blossom",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "tree plant sakura pink flowers spring petals japan",
    camera: { yaw: 0.5, pitch: 0.22, roll: 0, distance: 4.2 },
  },
  {
    id: "maple",
    label: "Maple tree",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "tree plant autumn fall leaves red orange",
    camera: { yaw: 0.5, pitch: 0.22, roll: 0, distance: 4.2 },
  },
  {
    id: "bonsai",
    label: "Bonsai",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "tree plant miniature pot japan zen",
    camera: { yaw: 0.45, pitch: 0.3, roll: 0, distance: 4.2 },
  },
  {
    id: "willow",
    label: "Weeping willow",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "tree plant weeping drooping river",
    camera: { yaw: 0.5, pitch: 0.22, roll: 0, distance: 4.2 },
  },
  {
    id: "sunflower",
    label: "Sunflower",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "flower plant summer yellow seeds petals",
    camera: { yaw: 0.3, pitch: 0.2, roll: 0, distance: 4.2 },
  },
  {
    id: "rose",
    label: "Rose",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "flower plant red love petals thorns valentine",
    camera: { yaw: 0.4, pitch: 0.25, roll: 0, distance: 4.2 },
  },
  {
    id: "dandelion",
    label: "Dandelion",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "flower plant seeds blow wish clock weed",
    camera: { yaw: 0.35, pitch: 0.2, roll: 0, distance: 4.2 },
  },
  {
    id: "tulip",
    label: "Tulips",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "flower plant spring bulb petals holland",
    camera: { yaw: 0.45, pitch: 0.25, roll: 0, distance: 4.2 },
  },
  {
    id: "daisy",
    label: "Daisies",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "flower plant white petals meadow spring",
    camera: { yaw: 0.4, pitch: 0.3, roll: 0, distance: 4.2 },
  },
  {
    id: "lotus",
    label: "Lotus",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "flower plant water lily pad pond pink",
    camera: { yaw: 0.45, pitch: 0.62, roll: 0, distance: 3.9 },
  },
  {
    id: "mushroom",
    label: "Toadstool",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "fungus fly agaric red spots forest fairy",
    camera: { yaw: 0.45, pitch: 0.3, roll: 0, distance: 4.2 },
  },
  {
    id: "fern",
    label: "Fern",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "plant frond forest fiddlehead green",
    camera: { yaw: 0.45, pitch: 0.32, roll: 0, distance: 3.8 },
  },
  {
    id: "saguaro",
    label: "Saguaro cactus",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "plant cactus desert spines arms succulent",
    camera: { yaw: 0.45, pitch: 0.2, roll: 0, distance: 4.2 },
  },
  {
    id: "coral",
    label: "Coral reef",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "sea ocean reef anemone fish underwater",
    camera: { yaw: 0.45, pitch: 0.3, roll: 0, distance: 3.7 },
  },
  {
    id: "pinecone",
    label: "Pinecone",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "pine cone seed scales forest tree",
    camera: { yaw: 0.45, pitch: 0.25, roll: 0, distance: 4.2 },
  },
  {
    id: "acorn",
    label: "Acorns",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "oak nut seed leaf autumn squirrel",
    camera: { yaw: 0.35, pitch: 0.45, roll: 0, distance: 3.6 },
  },
  {
    id: "succulent",
    label: "Succulent",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "plant rosette echeveria pot cactus",
    camera: { yaw: 0.45, pitch: 0.55, roll: 0, distance: 4.2 },
  },
  {
    id: "bamboo",
    label: "Bamboo",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "plant grass stalks panda asia green",
    camera: { yaw: 0.45, pitch: 0.2, roll: 0, distance: 4.2 },
  },
  {
    id: "rocks",
    label: "Pebbles",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "rock stone pile cairn pebble beach",
    camera: { yaw: 0.45, pitch: 0.35, roll: 0, distance: 3.9 },
  },
  {
    id: "kelp",
    label: "Kelp",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "seaweed sea ocean underwater forest algae",
    camera: { yaw: 0.45, pitch: 0.2, roll: 0, distance: 4.2 },
  },

  // ---- Pack: elements ----
  // (entries for src/packs/elements.js go here)
  {
    id: "storm-cloud",
    label: "Storm cloud",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "weather rain lightning thunder cloud storm",
    camera: { yaw: 0.4, pitch: 0.2, roll: 0, distance: 4.0 },
  },
  {
    id: "lava-lamp",
    label: "Lava lamp",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "lamp wax blobs retro groovy glow light",
    camera: { yaw: 0.4, pitch: 0.2, roll: 0, distance: 4.2 },
  },
  {
    id: "snow-globe",
    label: "Snow globe",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "snow winter glass shake snowman christmas",
    camera: { yaw: 0.4, pitch: 0.25, roll: 0, distance: 4.2 },
  },
  {
    id: "volcano",
    label: "Volcano",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "lava eruption magma island mountain smoke fire",
    camera: { yaw: 0.45, pitch: 0.3, roll: 0, distance: 4.2 },
  },
  {
    id: "ice-statue",
    label: "Ice swan",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "ice sculpture swan melt frozen cold statue",
    camera: { yaw: 0.35, pitch: 0.18, roll: 0, distance: 3.8 },
  },
  {
    id: "candle",
    label: "Candle",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "flame wax light fire birthday glow",
    camera: { yaw: 0.45, pitch: 0.25, roll: 0, distance: 4.2 },
  },
  {
    id: "tornado",
    label: "Tornado",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "twister wind storm funnel weather cyclone",
    camera: { yaw: 0.45, pitch: 0.15, roll: 0, distance: 4.2 },
  },
  {
    id: "rainbow",
    label: "Rainbow",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "weather colours arc clouds sky",
    camera: { yaw: 0.2, pitch: 0.15, roll: 0, distance: 4.0 },
  },
  {
    id: "iceberg",
    label: "Iceberg",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "ice sea ocean arctic cold floe glacier",
    camera: { yaw: 0.45, pitch: 0.2, roll: 0, distance: 4.2 },
  },
  {
    id: "waterfall",
    label: "Waterfall",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "water river cliff falls mist pool",
    camera: { yaw: 0.45, pitch: 0.25, roll: 0, distance: 4.2 },
  },
  {
    id: "ocean-wave",
    label: "Ocean wave",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "sea surf wave curl barrel water beach",
    camera: { yaw: 0.05, pitch: 0.15, roll: 0, distance: 4.2 },
  },
  {
    id: "geyser",
    label: "Geyser",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "steam water hot spring eruption",
    camera: { yaw: 0.45, pitch: 0.25, roll: 0, distance: 4.2 },
  },

  // ---- Pack: food ----
  {
    id: "ice-cream",
    label: "Ice cream",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "cone scoop gelato waffle melt sprinkles cherry sweet dessert",
    camera: { yaw: 0.55, pitch: 0.3, roll: 0, distance: 3.9 },
  },
  {
    id: "watermelon",
    label: "Watermelon",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fruit melon wedge slice seeds summer picnic",
    camera: { yaw: 0.55, pitch: 0.34, roll: 0, distance: 4.1 },
  },
  {
    id: "birthday-cake",
    label: "Birthday cake",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "party candles flames blow out frosting sprinkles layers sweet dessert",
    camera: { yaw: 0.55, pitch: 0.36, roll: 0, distance: 4.2 },
  },
  {
    id: "popcorn",
    label: "Popcorn",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "cinema movie snack bucket pop kernels butter",
    camera: { yaw: 0.55, pitch: 0.34, roll: 0, distance: 4.2 },
  },
  {
    id: "jelly",
    label: "Jelly",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "jello gelatin wobble wobbly dessert fruit pudding",
    camera: { yaw: 0.55, pitch: 0.4, roll: 0, distance: 4.1 },
  },
  {
    id: "pancakes",
    label: "Pancakes",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "breakfast stack syrup butter flip hotcakes",
    camera: { yaw: 0.55, pitch: 0.42, roll: 0, distance: 4.1 },
  },
  {
    id: "cupcake",
    label: "Cupcake",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fairy cake muffin frosting swirl sprinkles cherry sweet",
    camera: { yaw: 0.55, pitch: 0.3, roll: 0, distance: 4.0 },
  },
  {
    id: "lollipop",
    label: "Lollipop",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "candy swirl sweet rainbow stick sucker",
    camera: { yaw: 0.3, pitch: 0.2, roll: 0, distance: 4.0 },
  },
  {
    id: "candy-cane",
    label: "Candy cane",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "christmas peppermint stripes candy sweet bow",
    camera: { yaw: 0.3, pitch: 0.2, roll: 0, distance: 4.0 },
  },
  {
    id: "macarons",
    label: "Macarons",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "french biscuits pastel almond sweet stack",
    camera: { yaw: 0.55, pitch: 0.3, roll: 0, distance: 4.1 },
  },
  {
    id: "gummy-bear",
    label: "Gummy bear",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "candy jelly sweet bear chewy squish",
    camera: { yaw: 0.35, pitch: 0.2, roll: 0, distance: 4.0 },
  },
  {
    id: "pretzel",
    label: "Pretzel",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "bread knot salt baked snack bakery",
    camera: { yaw: 0.3, pitch: 0.25, roll: 0, distance: 4.1 },
  },
  {
    id: "croissant",
    label: "Croissant",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "pastry bakery breakfast french flaky butter",
    camera: { yaw: 0.45, pitch: 0.95, roll: 0, distance: 3.9 },
  },
  {
    id: "pizza",
    label: "Pizza",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "pepperoni margherita cheese slice italian basil dinner",
    camera: { yaw: 0.55, pitch: 0.72, roll: 0, distance: 3.9 },
  },
  {
    id: "burger",
    label: "Burger",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "hamburger cheeseburger bun sesame lettuce tomato cheese patty",
    camera: { yaw: 0.55, pitch: 0.3, roll: 0, distance: 4.0 },
  },
  {
    id: "sushi",
    label: "Sushi",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "japanese nigiri maki roll salmon tuna rice chopsticks wasabi",
    camera: { yaw: 0.45, pitch: 0.62, roll: 0, distance: 3.7 },
  },
  {
    id: "taco",
    label: "Taco",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "mexican shell lettuce cheese tomato beef",
    camera: { yaw: 0.4, pitch: 0.3, roll: 0, distance: 3.9 },
  },
  {
    id: "egg",
    label: "Boiled egg",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "breakfast egg cup yolk toast soldiers crack",
    camera: { yaw: 0.45, pitch: 0.3, roll: 0, distance: 4.1 },
  },
  {
    id: "coffee",
    label: "Coffee",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "latte cappuccino cup saucer drink steam cafe art",
    camera: { yaw: 0.55, pitch: 0.58, roll: 0, distance: 4.0 },
  },
  {
    id: "apple",
    label: "Apple",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fruit red green golden leaf orchard",
    camera: { yaw: 0.55, pitch: 0.3, roll: 0, distance: 4.1 },
  },
  {
    id: "banana",
    label: "Bananas",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fruit bunch yellow tropical",
    camera: { yaw: 0.3, pitch: 0.35, roll: 0, distance: 4.2 },
  },
  {
    id: "orange",
    label: "Orange",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fruit citrus segments half juicy leaf",
    camera: { yaw: 0.55, pitch: 0.36, roll: 0, distance: 4.2 },
  },
  {
    id: "kiwi",
    label: "Kiwi",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fruit kiwifruit green seeds half fuzzy",
    camera: { yaw: 0.55, pitch: 0.36, roll: 0, distance: 4.2 },
  },
  {
    id: "pineapple",
    label: "Pineapple",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fruit tropical crown leaves spiky",
    camera: { yaw: 0.55, pitch: 0.25, roll: 0, distance: 4.1 },
  },
  {
    id: "cherries",
    label: "Cherries",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fruit cherry pair stems red glossy",
    camera: { yaw: 0.35, pitch: 0.25, roll: 0, distance: 4.1 },
  },
  {
    id: "grapes",
    label: "Grapes",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fruit bunch vine purple green leaf",
    camera: { yaw: 0.45, pitch: 0.25, roll: 0, distance: 4.1 },
  },
  {
    id: "avocado",
    label: "Avocado",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fruit halves stone pit green guacamole",
    camera: { yaw: 0.55, pitch: 0.45, roll: 0, distance: 4.2 },
  },

  // ---- Pack: playthings ----
  {
    id: "bricks",
    label: "Building bricks",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "blocks studs stack build construction plastic",
    camera: { yaw: 0.6, pitch: 0.42, roll: 0, distance: 4.4 },
  },
  {
    id: "rubber-duck",
    label: "Rubber duck",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "bath duckie yellow squeak",
    camera: { yaw: 0.95, pitch: 0.22, roll: 0, distance: 4.4 },
  },
  {
    id: "spinning-top",
    label: "Spinning top",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "spin whirl gyroscope precession",
    camera: { yaw: 0.5, pitch: 0.3, roll: 0, distance: 4.5 },
  },
  {
    id: "dice",
    label: "Dice",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "die d6 d20 roll pips game chance",
    camera: { yaw: 0.45, pitch: 0.5, roll: 0, distance: 4.4 },
  },
  {
    id: "newtons-cradle",
    label: "Newton's cradle",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "pendulum balls swing desk physics momentum",
    camera: { yaw: 0.35, pitch: 0.25, roll: 0, distance: 4.4 },
  },
  {
    id: "teddy-bear",
    label: "Teddy bear",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "bear plush soft cuddly stuffed",
    camera: { yaw: 0.3, pitch: 0.18, roll: 0, distance: 4.5 },
  },
  {
    id: "yo-yo",
    label: "Yo-yo",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "yoyo string spin throw",
    camera: { yaw: 0.35, pitch: 0.12, roll: 0, distance: 3.9 },
  },
  {
    id: "puzzle-cube",
    label: "Puzzle cube",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "twist cube colours puzzle 3x3",
    camera: { yaw: 0.62, pitch: 0.5, roll: 0, distance: 7.4 },
  },
  {
    id: "spring-toy",
    label: "Spring toy",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "coil slinky rainbow stairs walk",
    camera: { yaw: 0.25, pitch: 0.3, roll: 0, distance: 4.4 },
  },
  {
    id: "kite",
    label: "Kite",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "wind fly diamond tail string sky",
    camera: { yaw: 0.2, pitch: 0.1, roll: 0, distance: 4.4 },
  },
  {
    id: "paper-plane",
    label: "Paper plane",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "paper aeroplane airplane dart fold fly",
    camera: { yaw: 0.7, pitch: 0.42, roll: 0, distance: 3.6 },
  },
  {
    id: "origami-crane",
    label: "Origami crane",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "paper fold bird japan crane",
    camera: { yaw: 0.35, pitch: 0.3, roll: 0, distance: 3.7 },
  },
  {
    id: "balloon-dog",
    label: "Balloon dog",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "balloon animal twist party pop",
    camera: { yaw: 0.2, pitch: 0.2, roll: 0, distance: 4.4 },
  },
  {
    id: "soap-bubbles",
    label: "Soap bubbles",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "bubble wand iridescent float blow",
    camera: { yaw: 0.2, pitch: 0.15, roll: 0, distance: 4.4 },
  },
  {
    id: "robot",
    label: "Wind-up robot",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "robot tin clockwork key antenna retro",
    camera: { yaw: 0.45, pitch: 0.2, roll: 0, distance: 4.5 },
  },

  // ---- Pack: maths ----
  {
    id: "lorenz",
    label: "Lorenz attractor",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "chaos butterfly strange attractor curve differential equations",
    camera: { yaw: 0.15, pitch: 0.12, roll: 0, distance: 4.2 },
  },
  {
    id: "mobius",
    label: "Möbius strip",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "mobius moebius band one side twist topology surface",
    camera: { yaw: 0.9, pitch: 0.22, roll: 0, distance: 4.3 },
  },
  {
    id: "klein-bottle",
    label: "Klein bottle",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "topology surface glass bottle non-orientable",
    camera: { yaw: 0.5, pitch: 0.2, roll: 0, distance: 4.4 },
  },
  {
    id: "menger-sponge",
    label: "Menger sponge",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "fractal cube holes sponge recursive",
    camera: { yaw: 0.62, pitch: 0.5, roll: 0, distance: 7.2 },
  },
  {
    id: "hypercube",
    label: "Hypercube",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "tesseract 4d four dimensions cube projection",
    camera: { yaw: 0.55, pitch: 0.35, roll: 0, distance: 6.4 },
  },
  {
    id: "torus-knot",
    label: "Torus knot",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "knot trefoil topology tube curve",
    camera: { yaw: 0.2, pitch: 0.3, roll: 0, distance: 4.2 },
  },
  {
    id: "gyroid",
    label: "Gyroid",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "minimal surface triply periodic labyrinth",
    camera: { yaw: 0.62, pitch: 0.45, roll: 0, distance: 6.8 },
  },
  {
    id: "mandelbulb",
    label: "Mandelbulb",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "fractal 3d mandelbrot bulb",
    camera: { yaw: 0.5, pitch: 0.35, roll: 0, distance: 4.4 },
  },
  {
    id: "sierpinski",
    label: "Sierpinski tetrahedron",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "fractal triangle pyramid tetrix recursive",
    camera: { yaw: 0.5, pitch: 0.3, roll: 0, distance: 4.4 },
  },
  {
    id: "platonic",
    label: "Platonic solids",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "polyhedron tetrahedron cube octahedron dodecahedron icosahedron geometry",
    camera: { yaw: 0.5, pitch: 0.35, roll: 0, distance: 5.2 },
  },
  {
    id: "seashell-spiral",
    label: "Seashell spiral",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "spiral shell logarithmic conch snail growth",
    camera: { yaw: 0.5, pitch: 0.85, roll: 0, distance: 3.8 },
  },

  // ---- Pack: objects ----
  {
    id: "book",
    label: "Storybook",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "book pages read story hardcover open close flip",
    camera: { yaw: 0.25, pitch: 0.78, roll: 0, distance: 3.9 },
  },
  {
    id: "laptop",
    label: "Laptop",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "computer notebook screen keyboard open close",
    camera: { yaw: 0.45, pitch: 0.32, roll: 0, distance: 4.6 },
  },
  {
    id: "music-box",
    label: "Music box",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "ballerina dancer jewellery box lid tune",
    camera: { yaw: 0.4, pitch: 0.35, roll: 0, distance: 4.6 },
  },
  {
    id: "clock",
    label: "Alarm clock",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "clock time bells alarm ring hands",
    camera: { yaw: 0.3, pitch: 0.12, roll: 0, distance: 4.4 },
  },
  {
    id: "gift-box",
    label: "Gift box",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "present birthday ribbon bow surprise confetti",
    camera: { yaw: 0.5, pitch: 0.38, roll: 0, distance: 4.8 },
  },
  {
    id: "umbrella",
    label: "Umbrella",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "rain parasol canopy open close",
    camera: { yaw: 0.4, pitch: 0.3, roll: 0, distance: 4.3 },
  },
  {
    id: "desk-fan",
    label: "Desk fan",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "fan blades spin breeze oscillating retro",
    camera: { yaw: 0.35, pitch: 0.2, roll: 0, distance: 4.4 },
  },
  {
    id: "lamp",
    label: "Desk lamp",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "lamp light bulb switch anglepoise",
    camera: { yaw: 0.2, pitch: 0.25, roll: 0, distance: 4.4 },
  },
  {
    id: "potion-bottle",
    label: "Potion bottle",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "magic flask glow cork bubbles wizard",
    camera: { yaw: 0.4, pitch: 0.2, roll: 0, distance: 4.4 },
  },
  {
    id: "telescope",
    label: "Telescope",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "brass spyglass tripod stars astronomy extend",
    camera: { yaw: 0.35, pitch: 0.2, roll: 0, distance: 4.4 },
  },

  // ---- Pack: medieval ----
  // (entries for src/packs/medieval.js go here)

  // ---- Pack: animals ----
  // (entries for src/packs/animals.js go here)

  // ---- Pack: holidays ----
  // (entries for src/packs/holidays.js go here)

  // ---- Pack: music ----
  // (entries for src/packs/music.js go here)

  // ---- Pack: vehicles ----
  // (entries for src/packs/vehicles.js go here)

  // ---- Pack: landmarks ----
  // (entries for src/packs/landmarks.js go here)
];

export function findToy(id) {
  return TOYS.find((t) => t.id === id) || null;
}

export function categoryLabel(id) {
  return CATEGORIES.find((c) => c.id === id)?.label || "";
}

// Categories that have at least one toy, in shelf order.
export function shelfCategories() {
  return CATEGORIES.filter((c) => TOYS.some((t) => t.category === c.id));
}

// Lower-case, accent-free text for search matching.
export function foldText(text) {
  return String(text || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase();
}

// Toys matching a search: every word must appear in the label, the
// category name or the toy's search words. Label matches come first.
export function searchToys(query, toys = TOYS) {
  const words = foldText(query).split(/\s+/).filter(Boolean);
  if (!words.length) return toys.slice();
  const scored = [];
  for (const t of toys) {
    const label = foldText(t.label);
    const hay = `${label} ${foldText(categoryLabel(t.category))} ${foldText(t.tags)} ${t.id}`;
    if (!words.every((w) => hay.includes(w))) continue;
    const score = words.reduce(
      (n, w) => n + (label.startsWith(w) ? 3 : label.includes(w) ? 2 : 0),
      0,
    );
    scored.push({ t, score });
  }
  return scored.sort((a, b) => b.score - a.score).map((s) => s.t);
}

// Resolves an asset path against the Splashery root (works from the app,
// the embed page and the custom element on another site).
export const ROOT = new URL("../", import.meta.url);

export function assetURL(path) {
  return new URL(path, ROOT).href;
}

export function thumbURL(toy) {
  return assetURL(`assets/toys/${toy.id}/thumb.webp`);
}
