// The toy shelf: built-in toys. Captured toys are SOG files under
// assets/toys/<id>/ (prepared with tools/prepare-assets.mjs, credits in
// CREDITS.md); procedural toys are generator presets built in the browser.
//
// This catalogue is metadata only (ids, labels, categories, search words) so
// it stays small as the shelf grows; toy code that needs more than a
// generator preset lives in per-pack modules that load when a toy is picked.

// Shelf categories, in shelf order. A category only shows once it has toys.
export const CATEGORIES = [
  { id: "scans", label: "Photoreal" },
  { id: "shapes", label: "Shapes" },
  { id: "balls", label: "Balls" },
  { id: "space", label: "Space" },
  { id: "tiny", label: "Tiny world" },
  { id: "atoms", label: "Atoms" },
  { id: "gems", label: "Gems" },
  { id: "anatomy", label: "Body" },
  { id: "nature", label: "Nature" },
  { id: "weather", label: "Weather & fire" },
  { id: "food", label: "Food" },
  { id: "toys", label: "Toys" },
  { id: "objects", label: "Open me" },
  { id: "medieval", label: "Medieval" },
  { id: "animals", label: "Animals" },
  { id: "maths", label: "Maths" },
  { id: "holidays", label: "Holidays" },
  { id: "music", label: "Music" },
  { id: "vehicles", label: "Vehicles" },
  { id: "landmarks", label: "Landmarks" },
];

export const TOYS = [
  {
    id: "cactus",
    label: "Cactus",
    category: "scans",
    tags: "plant succulent pot captured photo real",
    kind: "captured",
    url: "assets/toys/cactus/cactus.sog",
    urlWeak: "assets/toys/cactus/cactus-lite.sog",
    credit: {
      title: "Cactus (3DGS sample data)",
      author: "steam studio / 3D SCAN STUDIO iris",
      source: "https://note.com/steam_studio/n/ne9736d94f162",
      license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      changes: "Converted to SOG, spherical harmonics removed, recentred, scaled and cropped.",
    },
  },
  {
    id: "strawberry",
    label: "Strawberry",
    category: "scans",
    tags: "fruit food berry captured photo real",
    kind: "captured",
    url: "assets/toys/strawberry/strawberry.sog",
    urlWeak: "assets/toys/strawberry/strawberry-lite.sog",
    camera: { yaw: 0.25, pitch: 0.3, roll: 0, distance: 5.6 },
    credit: {
      title: "Strawberry",
      author: "Dany Bittel",
      source: "https://superspl.at/scene/84df8849",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes: "Converted, decimated, spherical harmonics removed, recentred and scaled.",
    },
  },
  {
    id: "cookie",
    label: "Heart cookie",
    category: "scans",
    tags: "food biscuit heart sweet captured photo real",
    kind: "captured",
    url: "assets/toys/cookie/cookie.sog",
    urlWeak: "assets/toys/cookie/cookie-lite.sog",
    credit: {
      title: "Heart Cookie",
      author: "Dany Bittel",
      source: "https://superspl.at/scene/bd964899",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes: "Converted, spherical harmonics removed, recentred and scaled.",
    },
  },
  {
    id: "bee",
    label: "Honeybee",
    category: "scans",
    tags: "insect animal bug honeybee captured photo real",
    kind: "captured",
    url: "assets/toys/bee/bee.sog",
    urlWeak: "assets/toys/bee/bee-lite.sog",
    credit: {
      title: "Japanese Bee",
      author: "YUMA Co., Ltd.",
      source: "https://superspl.at/scene/ae58ed2c",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, spherical harmonics removed, turned upright, recentred and scaled.",
    },
  },
  {
    id: "blob",
    label: "Jelly blob",
    category: "shapes",
    tags: "jelly noise candy generated",
    kind: "procedural",
    generator: {
      shape: "blob",
      palette: "candy",
      seed: 7,
      sizeJitter: 0.35,
      roughness: 0.25,
      colorNoise: 0.2,
    },
  },
  {
    id: "donut",
    label: "Donut",
    category: "shapes",
    tags: "doughnut torus food sprinkles frosting generated",
    kind: "procedural",
    generator: {
      shape: "torus",
      palette: "frosting",
      seed: 5,
      sizeJitter: 0.3,
      roughness: 0.2,
      colorNoise: 0.3,
    },
    camera: { yaw: 0.4, pitch: 0.62, roll: 0, distance: 5 },
  },
  {
    id: "knot",
    label: "Neon knot",
    category: "shapes",
    tags: "trefoil neon maths generated",
    kind: "procedural",
    generator: {
      shape: "knot",
      palette: "neon",
      seed: 11,
      sizeJitter: 0.3,
      roughness: 0.15,
      colorNoise: 0.15,
    },
  },
  {
    id: "planet",
    label: "Tiny planet",
    category: "shapes",
    tags: "earth world globe space generated v1",
    kind: "procedural",
    note: "A tribute to Splashery v1",
    generator: {
      shape: "sphere",
      palette: "planet",
      seed: 3,
      sizeJitter: 0.3,
      roughness: 0.2,
      colorNoise: 0.25,
    },
  },
  // ---- More captured scans (CC BY 4.0, from SuperSplat) ----
  {
    id: "cluster-fly",
    label: "Cluster fly",
    category: "scans",
    tags: "photoreal scan captured insect bug animal macro",
    kind: "captured",
    url: "assets/toys/cluster-fly/cluster-fly.sog",
    urlWeak: "assets/toys/cluster-fly/cluster-fly-lite.sog",
    credit: {
      title: "Cluster Fly",
      author: "Dany Bittel",
      source: "https://superspl.at/scene/285082b2",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes: "Converted, decimated, spherical harmonics removed, recentred and scaled.",
    },
  },
  {
    id: "may-beetle",
    label: "May beetle",
    category: "scans",
    tags: "photoreal scan captured insect bug animal cockchafer",
    kind: "captured",
    url: "assets/toys/may-beetle/may-beetle.sog",
    urlWeak: "assets/toys/may-beetle/may-beetle-lite.sog",
    credit: {
      title: "MAY-BEETLE-HIRES",
      author: "trilithon",
      source: "https://superspl.at/scene/9d4c4442",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes: "Converted, decimated, spherical harmonics removed, recentred and scaled.",
    },
  },
  {
    id: "millipede",
    label: "Millipede",
    category: "scans",
    tags: "photoreal scan captured insect bug animal legs",
    kind: "captured",
    url: "assets/toys/millipede/millipede.sog",
    urlWeak: "assets/toys/millipede/millipede-lite.sog",
    credit: {
      title: "millipede spec.",
      author: "scant3d",
      source: "https://superspl.at/scene/3d5482d4",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes: "Converted, decimated, spherical harmonics removed, recentred and scaled.",
    },
  },
  {
    id: "bumblebee",
    label: "Carder bumblebee",
    category: "scans",
    tags: "photoreal scan captured insect bee animal macro",
    kind: "captured",
    url: "assets/toys/bumblebee/bumblebee.sog",
    urlWeak: "assets/toys/bumblebee/bumblebee-lite.sog",
    credit: {
      title: "Macroscan - Brown-banded carder bumblebee (Bombus humilis)",
      author: "macroscans",
      source: "https://superspl.at/scene/65ff2330",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes: "Converted, decimated, spherical harmonics removed, recentred and scaled.",
    },
  },
  {
    id: "raspberry",
    label: "Raspberry",
    category: "scans",
    tags: "photoreal scan captured fruit food berry",
    kind: "captured",
    url: "assets/toys/raspberry/raspberry.sog",
    urlWeak: "assets/toys/raspberry/raspberry-lite.sog",
    credit: {
      title: "Raspberry",
      author: "Dany Bittel",
      source: "https://superspl.at/scene/04bdd392",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes: "Converted, decimated, spherical harmonics removed, recentred and scaled.",
    },
  },
  {
    id: "blackberry",
    label: "Blackberry",
    category: "scans",
    tags: "photoreal scan captured fruit food berry",
    kind: "captured",
    url: "assets/toys/blackberry/blackberry.sog",
    urlWeak: "assets/toys/blackberry/blackberry-lite.sog",
    credit: {
      title: "Blackberry",
      author: "Dany Bittel",
      source: "https://superspl.at/scene/827133e7",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes: "Converted, decimated, spherical harmonics removed, recentred and scaled.",
    },
  },
  {
    id: "blueberry",
    label: "Blueberry",
    category: "scans",
    tags: "photoreal scan captured fruit food berry",
    kind: "captured",
    url: "assets/toys/blueberry/blueberry.sog",
    urlWeak: "assets/toys/blueberry/blueberry-lite.sog",
    credit: {
      title: "Blueberry",
      author: "Dany Bittel",
      source: "https://superspl.at/scene/fd8b85a7",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes: "Converted, decimated, spherical harmonics removed, recentred and scaled.",
    },
  },
  {
    id: "grape",
    label: "Grape",
    category: "scans",
    tags: "photoreal scan captured fruit food",
    kind: "captured",
    url: "assets/toys/grape/grape.sog",
    urlWeak: "assets/toys/grape/grape-lite.sog",
    credit: {
      title: "Grape",
      author: "Dany Bittel",
      source: "https://superspl.at/scene/4ae563ac",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes: "Converted, decimated, spherical harmonics removed, recentred and scaled.",
    },
  },
  {
    id: "star-cookie",
    label: "Cinnamon star cookie",
    category: "scans",
    tags: "photoreal scan captured food biscuit christmas sweet",
    kind: "captured",
    url: "assets/toys/star-cookie/star-cookie.sog",
    urlWeak: "assets/toys/star-cookie/star-cookie-lite.sog",
    credit: {
      title: "Cinnamon Star Cookie",
      author: "Dany Bittel",
      source: "https://superspl.at/scene/6584b96e",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes:
        "Converted, decimated, spherical harmonics removed, turned to show the glazed top, recentred and scaled.",
    },
  },
  {
    id: "tomatoes",
    label: "Tomatoes",
    category: "scans",
    tags: "photoreal scan captured vegetable food",
    kind: "captured",
    url: "assets/toys/tomatoes/tomatoes.sog",
    urlWeak: "assets/toys/tomatoes/tomatoes-lite.sog",
    credit: {
      title: "Tomatoes - No Postshot!",
      author: "simonbethke",
      source: "https://superspl.at/scene/0101ad57",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes: "Converted, decimated, spherical harmonics removed, recentred and scaled.",
    },
  },
  {
    id: "mandeltorus",
    label: "Mandeltorus",
    category: "scans",
    tags: "photoreal scan captured maths fractal art",
    kind: "captured",
    url: "assets/toys/mandeltorus/mandeltorus.sog",
    urlWeak: "assets/toys/mandeltorus/mandeltorus-lite.sog",
    credit: {
      title: "MandelTorus 4,12,8,1.5 (Spirula Studio)",
      author: "harry7557558",
      source: "https://superspl.at/scene/e7088609",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes: "Converted, decimated, spherical harmonics removed, recentred and scaled.",
    },
  },
  {
    id: "basket",
    label: "Basket",
    category: "scans",
    tags: "photoreal scan captured wicker woven",
    kind: "captured",
    url: "assets/toys/basket/basket.sog",
    urlWeak: "assets/toys/basket/basket-lite.sog",
    // From above, so the shells show (from the side you see only wicker).
    camera: { yaw: 0.55, pitch: 0.78, roll: 0, distance: 4.6 },
    credit: {
      title: "Basket",
      author: "hollmar",
      source: "https://superspl.at/scene/efa1fa80",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      changes: "Converted, decimated, spherical harmonics removed, recentred and scaled.",
    },
  },
  // ---- Photoreal models (CC0 3D models turned into splats) ----
  {
    id: "rubber-duck-real",
    label: "Real rubber duck",
    category: "scans",
    tags: "photoreal model bath toy yellow model",
    kind: "captured",
    url: "assets/toys/rubber-duck-real/rubber-duck-real.sog",
    urlWeak: "assets/toys/rubber-duck-real/rubber-duck-real-lite.sog",
    credit: {
      title: "Rubber Duck Toy",
      author: "Plat251",
      source: "https://polyhaven.com/a/rubber_duck_toy",
      license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      changes:
        "Turned into splats from the textured 3D model (tools/mesh-to-splats.mjs), recentred and scaled.",
    },
  },
  {
    id: "garden-gnome",
    label: "Garden gnome",
    category: "scans",
    tags: "photoreal model garden hat beard statue",
    kind: "captured",
    url: "assets/toys/garden-gnome/garden-gnome.sog",
    urlWeak: "assets/toys/garden-gnome/garden-gnome-lite.sog",
    credit: {
      title: "Garden Gnome",
      author: "Bhargav Kubal",
      source: "https://polyhaven.com/a/garden_gnome",
      license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      changes:
        "Turned into splats from the textured 3D model (tools/mesh-to-splats.mjs), recentred and scaled.",
    },
  },
  {
    id: "wooden-elephant",
    label: "Wooden elephant",
    category: "scans",
    tags: "photoreal model carving animal wood",
    kind: "captured",
    url: "assets/toys/wooden-elephant/wooden-elephant.sog",
    urlWeak: "assets/toys/wooden-elephant/wooden-elephant-lite.sog",
    credit: {
      title: "Carved Wooden Elephant",
      author: "Greg Zaal",
      source: "https://polyhaven.com/a/carved_wooden_elephant",
      license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      changes:
        "Turned into splats from the textured 3D model (tools/mesh-to-splats.mjs) with soft studio light baked in, recentred and scaled.",
    },
  },
  {
    id: "marble-bust",
    label: "Marble bust",
    category: "scans",
    tags: "photoreal model sculpture statue head art",
    kind: "captured",
    url: "assets/toys/marble-bust/marble-bust.sog",
    urlWeak: "assets/toys/marble-bust/marble-bust-lite.sog",
    credit: {
      title: "Marble Bust 01",
      author: "Rico Cilliers",
      source: "https://polyhaven.com/a/marble_bust_01",
      license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      changes:
        "Turned into splats from the textured 3D model (tools/mesh-to-splats.mjs), recentred and scaled.",
    },
  },
  {
    id: "ukulele",
    label: "Ukulele",
    category: "scans",
    tags: "photoreal model music instrument guitar strings",
    kind: "captured",
    url: "assets/toys/ukulele/ukulele.sog",
    urlWeak: "assets/toys/ukulele/ukulele-lite.sog",
    credit: {
      title: "Ukulele 01",
      author: "Joseph Burgan",
      source: "https://polyhaven.com/a/Ukulele_01",
      license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      changes:
        "Turned into splats from the textured 3D model (tools/mesh-to-splats.mjs), recentred and scaled.",
    },
  },
  {
    id: "alarm-clock",
    label: "Alarm clock",
    category: "scans",
    tags: "photoreal model time bell",
    kind: "captured",
    url: "assets/toys/alarm-clock/alarm-clock.sog",
    urlWeak: "assets/toys/alarm-clock/alarm-clock-lite.sog",
    credit: {
      title: "Alarm Clock 01",
      author: "Yann Kervran, James Ray Cock",
      source: "https://polyhaven.com/a/alarm_clock_01",
      license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      changes:
        "Turned into splats from the textured 3D model (tools/mesh-to-splats.mjs), recentred and scaled.",
    },
  },
  {
    id: "vintage-camera",
    label: "Vintage camera",
    category: "scans",
    tags: "photoreal model photo retro film",
    kind: "captured",
    url: "assets/toys/vintage-camera/vintage-camera.sog",
    urlWeak: "assets/toys/vintage-camera/vintage-camera-lite.sog",
    credit: {
      title: "Camera 01",
      author: "Rajil Jose Macatangay",
      source: "https://polyhaven.com/a/Camera_01",
      license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      changes:
        "Turned into splats from the textured 3D model (tools/mesh-to-splats.mjs) with soft studio light baked in, recentred and scaled. The maker's and lens names printed on it were painted out.",
    },
  },
  {
    id: "boombox",
    label: "Boombox",
    category: "scans",
    tags: "photoreal model radio music stereo retro",
    kind: "captured",
    url: "assets/toys/boombox/boombox.sog",
    urlWeak: "assets/toys/boombox/boombox-lite.sog",
    credit: {
      title: "Boombox",
      author: "Thomas Paul Mouilleron",
      source: "https://polyhaven.com/a/boombox",
      license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      changes:
        "Turned into splats from the textured 3D model (tools/mesh-to-splats.mjs) with soft studio light baked in, recentred and scaled.",
    },
  },
  {
    id: "croissant-real",
    label: "Real croissant",
    category: "scans",
    tags: "photoreal model food pastry bakery",
    kind: "captured",
    url: "assets/toys/croissant-real/croissant-real.sog",
    urlWeak: "assets/toys/croissant-real/croissant-real-lite.sog",
    credit: {
      title: "Croissant",
      author: "Greg Zaal, Dario Barresi",
      source: "https://polyhaven.com/a/croissant",
      license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      changes:
        "Turned into splats from the textured 3D model (tools/mesh-to-splats.mjs), recentred and scaled.",
    },
  },
  {
    id: "carrot-cake",
    label: "Carrot cake",
    category: "scans",
    tags: "photoreal model food dessert cake slice",
    kind: "captured",
    url: "assets/toys/carrot-cake/carrot-cake.sog",
    urlWeak: "assets/toys/carrot-cake/carrot-cake-lite.sog",
    credit: {
      title: "Carrot Cake",
      author: "Greg Zaal, James Ray Cock",
      source: "https://polyhaven.com/a/carrot_cake",
      license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      changes:
        "Turned into splats from the textured 3D model (tools/mesh-to-splats.mjs), recentred and scaled.",
    },
  },
  {
    id: "pomegranate",
    label: "Pomegranate",
    category: "scans",
    tags: "photoreal model food fruit",
    kind: "captured",
    url: "assets/toys/pomegranate/pomegranate.sog",
    urlWeak: "assets/toys/pomegranate/pomegranate-lite.sog",
    credit: {
      title: "Food Pomegranate 01",
      author: "Oliver Harries",
      source: "https://polyhaven.com/a/food_pomegranate_01",
      license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      changes:
        "Turned into splats from the textured 3D model (tools/mesh-to-splats.mjs), recentred and scaled.",
    },
  },
  {
    id: "lantern",
    label: "Lantern",
    category: "scans",
    tags: "photoreal model light lamp camping",
    kind: "captured",
    url: "assets/toys/lantern/lantern.sog",
    urlWeak: "assets/toys/lantern/lantern-lite.sog",
    credit: {
      title: "Lantern 01",
      author: "Rajil Jose Macatangay",
      source: "https://polyhaven.com/a/Lantern_01",
      license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      changes:
        "Turned into splats from the textured 3D model (tools/mesh-to-splats.mjs), recentred and scaled.",
    },
  },
  {
    id: "cat-statue",
    label: "Cat statue",
    category: "scans",
    tags: "photoreal model animal cat concrete statue",
    kind: "captured",
    url: "assets/toys/cat-statue/cat-statue.sog",
    urlWeak: "assets/toys/cat-statue/cat-statue-lite.sog",
    credit: {
      title: "Concrete Cat Statue",
      author: "Rico Cilliers, Riley Queen",
      source: "https://polyhaven.com/a/concrete_cat_statue",
      license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      changes:
        "Turned into splats from the textured 3D model (tools/mesh-to-splats.mjs), recentred and scaled.",
    },
  },
  {
    id: "horse-statue",
    label: "Horse statue",
    category: "scans",
    tags: "photoreal model animal horse sculpture",
    kind: "captured",
    url: "assets/toys/horse-statue/horse-statue.sog",
    urlWeak: "assets/toys/horse-statue/horse-statue-lite.sog",
    credit: {
      title: "Horse Statue 01",
      author: "Rico Cilliers",
      source: "https://polyhaven.com/a/horse_statue_01",
      license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      changes:
        "Turned into splats from the textured 3D model (tools/mesh-to-splats.mjs) with soft studio light baked in, recentred and scaled.",
    },
  },
  // Kit toys: recipes in src/packs/<pack>.js, built in the browser.
  {
    id: "basketball",
    label: "Basketball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball hoops court orange",
  },
  {
    id: "soccer-ball",
    label: "Soccer ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball football association pentagon hexagon",
  },
  {
    id: "american-football",
    label: "American football",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball gridiron laces pigskin",
    camera: { yaw: 0.35, pitch: 0.62, roll: 0, distance: 5 },
  },
  {
    id: "tennis-ball",
    label: "Tennis ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball felt fuzzy yellow racket",
  },
  {
    id: "baseball",
    label: "Baseball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball stitches bat diamond",
  },
  {
    id: "softball",
    label: "Softball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball stitches yellow",
  },
  {
    id: "beach-ball",
    label: "Beach ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball inflatable summer stripes",
  },
  {
    id: "golf-ball",
    label: "Golf ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball dimples tee",
  },
  {
    id: "rugby-ball",
    label: "Rugby ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball oval try",
  },
  {
    id: "volleyball",
    label: "Volleyball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball net beach panels",
  },
  {
    id: "water-polo-ball",
    label: "Water polo ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball pool swim grip",
  },
  {
    id: "ping-pong-ball",
    label: "Ping-pong ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball table tennis small",
  },
  {
    id: "cricket-ball",
    label: "Cricket ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball leather seam red",
  },
  {
    id: "bowling-ball",
    label: "Bowling ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball pins lane holes",
  },
  {
    id: "pool-ball",
    label: "Pool ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball billiards snooker cue eight number",
  },
  {
    id: "pickleball",
    label: "Pickleball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball paddle holes wiffle",
  },
  {
    id: "dodgeball",
    label: "Dodgeball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball playground rubber",
  },
  {
    id: "medicine-ball",
    label: "Medicine ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball gym workout heavy",
  },
  {
    id: "lacrosse-ball",
    label: "Lacrosse ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball rubber stick",
  },
  {
    id: "squash-ball",
    label: "Squash ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball racquet dots",
  },
  {
    id: "bouncy-ball",
    label: "Bouncy ball",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball super rubber swirl",
  },
  {
    id: "marble",
    label: "Marble",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball glass cats eye",
  },
  {
    id: "hockey-puck",
    label: "Hockey puck",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball ice rink",
  },
  {
    id: "shuttlecock",
    label: "Shuttlecock",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball badminton birdie feathers",
  },
  {
    id: "flying-disc",
    label: "Flying disc",
    category: "balls",
    kind: "kit",
    pack: "balls",
    tags: "sport ball throw frisbee catch",
  },
  {
    id: "heart",
    label: "Beating heart",
    category: "anatomy",
    kind: "kit",
    pack: "anatomy",
    tags: "organ body cardio pulse love valentine",
  },
  {
    id: "campfire",
    label: "Campfire",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "fire flame camping logs embers sparks",
    camera: { yaw: 0.5, pitch: 0.38, roll: 0, distance: 5 },
  },
  {
    id: "chest",
    label: "Treasure chest",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "pirate gold coins gems box lid open close",
    camera: { yaw: 0.45, pitch: 0.42, roll: 0, distance: 5.4 },
  },
  // ---- Pack: space ----
  {
    id: "sun",
    label: "Sun",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "star solar corona prominence sunspot hot yellow",
  },
  {
    id: "solar-system",
    label: "Solar system",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "orrery planets orbits sun model",
    camera: { yaw: 0.55, pitch: 0.72, roll: 0, distance: 3.7 },
  },
  {
    id: "mercury",
    label: "Mercury",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planet craters grey rocky small solar system",
  },
  {
    id: "venus",
    label: "Venus",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planet clouds yellow hot solar system",
  },
  {
    id: "earth",
    label: "Earth",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planet world globe ocean continents clouds home blue",
  },
  {
    id: "moon",
    label: "Moon",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "lunar craters maria grey satellite",
  },
  {
    id: "mars",
    label: "Mars",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planet red rust polar cap solar system",
  },
  {
    id: "jupiter",
    label: "Jupiter",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planet gas giant bands great red spot storm",
  },
  {
    id: "saturn",
    label: "Saturn",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planet rings gas giant bands",
    camera: { yaw: 0.55, pitch: 0.28, roll: 0, distance: 4.3 },
  },
  {
    id: "uranus",
    label: "Uranus",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planet ice giant cyan rings tilted",
    camera: { yaw: 0.55, pitch: 0.28, roll: 0, distance: 4.5 },
  },
  {
    id: "neptune",
    label: "Neptune",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planet ice giant blue dark spot wind",
  },
  {
    id: "aurora-planet",
    label: "Aurora world",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planet night aurora northern lights city lights earth",
  },
  {
    id: "asteroid",
    label: "Asteroid",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "rock space potato craters tumble",
  },
  {
    id: "comet",
    label: "Comet",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "ice tail dust coma nucleus",
  },
  {
    id: "meteor",
    label: "Meteor",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "shooting star fireball rock fire trail falling",
  },
  {
    id: "star",
    label: "Star",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "sun red dwarf blue giant white dwarf twinkle",
  },
  {
    id: "pulsar",
    label: "Pulsar",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "neutron star beams lighthouse spin magnetic",
  },
  {
    id: "black-hole",
    label: "Black hole",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "accretion disk event horizon gravity lensing",
    camera: { yaw: 0.55, pitch: 0.16, roll: 0, distance: 4.4 },
  },
  {
    id: "star-cluster",
    label: "Star cluster",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "globular cluster stars twinkle",
  },
  {
    id: "planetary-nebula",
    label: "Ring nebula",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "planetary nebula shell gas dying star ring",
    camera: { yaw: 0.35, pitch: 0.3, roll: 0, distance: 4.6 },
  },
  {
    id: "nebula",
    label: "Nebula",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "gas cloud pillars stars emission colourful",
    camera: { yaw: 0, pitch: 0.06, roll: 0, distance: 4.4 },
  },
  {
    id: "supernova",
    label: "Supernova",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "explosion star remnant debris blast",
  },
  {
    id: "spiral-galaxy",
    label: "Spiral galaxy",
    category: "space",
    kind: "kit",
    pack: "space",
    tags: "milky way andromeda stars arms barred",
    camera: { yaw: 0.55, pitch: 0.9, roll: 0, distance: 3.5 },
  },

  // ---- Pack: tiny ----
  // (entries for src/packs/tiny.js go here)
  {
    id: "virus",
    label: "Virus",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "microbe germ capsid spikes icosahedron microscope biology",
  },
  {
    id: "bacteriophage",
    label: "Bacteriophage",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "phage virus microbe tail fibres lander inject dna microscope biology",
    camera: { yaw: 0.55, pitch: 0.2, roll: 0, distance: 4.4 },
  },
  {
    id: "bacterium",
    label: "Bacterium",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "microbe germ bacteria rod flagella pili swim microscope biology",
  },
  {
    id: "red-blood-cell",
    label: "Red blood cell",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "cell blood erythrocyte disc body microscope biology",
  },
  {
    id: "neuron",
    label: "Neuron",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "nerve cell brain axon dendrite myelin synapse signal microscope biology",
    camera: { yaw: 0.55, pitch: 0.28, roll: 0, distance: 4.5 },
  },
  {
    id: "astrocyte",
    label: "Astrocyte",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "glia glial star cell brain nerve end feet microscope biology",
  },
  {
    id: "animal-cell",
    label: "Animal cell",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "cell nucleus mitochondria golgi organelles membrane microscope biology",
  },
  {
    id: "dna",
    label: "DNA",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "double helix gene genome base pairs unzip molecule biology",
    camera: { yaw: 0.55, pitch: 0.28, roll: 0, distance: 4.5 },
  },
  {
    id: "white-blood-cell",
    label: "White blood cell",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "cell blood immune leukocyte neutrophil granules body microscope biology",
  },
  {
    id: "microglia",
    label: "Microglia",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "glia glial cell brain immune branches microscope biology",
  },
  {
    id: "diatom",
    label: "Diatom",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "algae plankton glass silica shell pores ocean microscope biology",
    camera: { yaw: 0.55, pitch: 0.45, roll: 0, distance: 5 },
  },
  {
    id: "tardigrade",
    label: "Tardigrade",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "water bear moss piglet animal legs claws cute microscope biology",
  },
  {
    id: "pollen",
    label: "Pollen grain",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "plant flower spiky allergy sunflower pine lily microscope biology",
  },
  {
    id: "snowflake",
    label: "Snowflake",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "snow ice crystal winter frost six hexagon weather",
    camera: { yaw: 0.3, pitch: 0.15, roll: 0, distance: 5 },
  },
  {
    id: "chromosome",
    label: "Chromosome",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "dna gene chromatid centromere genetics cell biology",
  },
  {
    id: "mitochondrion",
    label: "Mitochondrion",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "mitochondria cell powerhouse energy cristae organelle biology",
  },
  {
    id: "paramecium",
    label: "Paramecium",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "protist ciliate cilia pond water swim microscope biology",
  },
  {
    id: "amoeba",
    label: "Amoeba",
    category: "tiny",
    kind: "kit",
    pack: "tiny",
    tags: "protist blob pseudopod pond water microscope biology",
    camera: { yaw: 0.55, pitch: 0.5, roll: 0, distance: 5 },
  },

  // ---- Pack: atoms ----
  // (entries for src/packs/atoms.js go here)
  {
    id: "orbital",
    label: "Electron orbital",
    category: "atoms",
    kind: "kit",
    pack: "atoms",
    tags: "atom electron cloud quantum wave function hydrogen chemistry physics",
  },
  {
    id: "atom",
    label: "Atom",
    category: "atoms",
    kind: "kit",
    pack: "atoms",
    tags: "bohr element nucleus proton neutron electron shell periodic table chemistry physics",
  },
  {
    id: "molecule",
    label: "Molecule",
    category: "atoms",
    kind: "kit",
    pack: "atoms",
    tags: "ball stick water caffeine benzene methane ethanol buckyball chemistry smiles formula mol sdf",
  },
  {
    id: "protein",
    label: "Protein",
    category: "atoms",
    kind: "kit",
    pack: "atoms",
    tags: "protein pdb ribbon helix strand ubiquitin insulin gfp hemoglobin biology chemistry",
  },
  {
    id: "crystal-lattice",
    label: "Crystal lattice",
    category: "atoms",
    kind: "kit",
    pack: "atoms",
    tags: "salt diamond graphite ice crystal structure atoms chemistry",
  },

  // ---- Pack: gems ----
  // (entries for src/packs/gems.js go here)
  {
    id: "diamond",
    label: "Diamond",
    category: "gems",
    kind: "kit",
    pack: "gems",
    tags: "gem jewel brilliant cut sparkle stone mineral",
  },
  {
    id: "ruby",
    label: "Ruby",
    category: "gems",
    kind: "kit",
    pack: "gems",
    tags: "gem jewel red oval cut stone mineral",
  },
  {
    id: "emerald",
    label: "Emerald",
    category: "gems",
    kind: "kit",
    pack: "gems",
    tags: "gem jewel green step cut stone mineral",
  },
  {
    id: "amethyst-geode",
    label: "Amethyst geode",
    category: "gems",
    kind: "kit",
    pack: "gems",
    tags: "gem crystal purple rock cave open quartz mineral",
  },
  {
    id: "sapphire",
    label: "Sapphire",
    category: "gems",
    kind: "kit",
    pack: "gems",
    tags: "gem jewel blue cushion cut stone mineral",
  },
  {
    id: "quartz-cluster",
    label: "Quartz cluster",
    category: "gems",
    kind: "kit",
    pack: "gems",
    tags: "crystal points rock clear mineral",
  },
  {
    id: "opal",
    label: "Opal",
    category: "gems",
    kind: "kit",
    pack: "gems",
    tags: "gem jewel rainbow play of colour cabochon stone mineral",
  },
  {
    id: "pearl",
    label: "Pearl",
    category: "gems",
    kind: "kit",
    pack: "gems",
    tags: "gem jewel oyster shell lustre sea open",
  },
  {
    id: "crystal-ball",
    label: "Crystal ball",
    category: "gems",
    kind: "kit",
    pack: "gems",
    tags: "glass orb magic mist fortune stand swirl",
  },

  // ---- Pack: anatomy ----
  // (entries for src/packs/anatomy.js go here)
  {
    id: "brain",
    label: "Brain",
    category: "anatomy",
    kind: "kit",
    pack: "anatomy",
    tags: "organ body mind think lobes cerebrum cerebellum neuron nerve",
  },
  {
    id: "eye",
    label: "Eye",
    category: "anatomy",
    kind: "kit",
    pack: "anatomy",
    tags: "organ body eyeball iris pupil see vision look",
  },
  {
    id: "lungs",
    label: "Lungs",
    category: "anatomy",
    kind: "kit",
    pack: "anatomy",
    tags: "organ body breathe air trachea bronchi respiration",
    camera: { yaw: 0.35, pitch: 0.2, roll: 0, distance: 5 },
  },
  {
    id: "tooth",
    label: "Tooth",
    category: "anatomy",
    kind: "kit",
    pack: "anatomy",
    tags: "molar teeth dentist enamel root body mouth",
  },
  {
    id: "kidney",
    label: "Kidney",
    category: "anatomy",
    kind: "kit",
    pack: "anatomy",
    tags: "organ body bean urine filter renal",
  },

  // ---- Pack: nature ----
  // (entries for src/packs/nature.js go here)
  {
    id: "oak",
    label: "Oak tree",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "tree plant leaves branches forest acorn season autumn winter",
    camera: { yaw: 0.5, pitch: 0.22, roll: 0, distance: 4.2 },
  },
  {
    id: "pine",
    label: "Pine tree",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "tree plant conifer evergreen fir spruce forest needles snow christmas",
    camera: { yaw: 0.5, pitch: 0.22, roll: 0, distance: 4.2 },
  },
  {
    id: "palm",
    label: "Palm tree",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "tree plant tropical beach island coconut fronds",
    camera: { yaw: 0.5, pitch: 0.22, roll: 0, distance: 4.2 },
  },
  {
    id: "cherry-blossom",
    label: "Cherry blossom",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "tree plant sakura pink flowers spring petals japan",
    camera: { yaw: 0.5, pitch: 0.22, roll: 0, distance: 4.2 },
  },
  {
    id: "maple",
    label: "Maple tree",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "tree plant autumn fall leaves red orange",
    camera: { yaw: 0.5, pitch: 0.22, roll: 0, distance: 4.2 },
  },
  {
    id: "bonsai",
    label: "Bonsai",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "tree plant miniature pot japan zen",
    camera: { yaw: 0.45, pitch: 0.3, roll: 0, distance: 4.2 },
  },
  {
    id: "willow",
    label: "Weeping willow",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "tree plant weeping drooping river",
    camera: { yaw: 0.5, pitch: 0.22, roll: 0, distance: 4.2 },
  },
  {
    id: "sunflower",
    label: "Sunflower",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "flower plant summer yellow seeds petals",
    camera: { yaw: 0.3, pitch: 0.2, roll: 0, distance: 4.2 },
  },
  {
    id: "rose",
    label: "Rose",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "flower plant red love petals thorns valentine",
    camera: { yaw: 0.4, pitch: 0.25, roll: 0, distance: 4.2 },
  },
  {
    id: "dandelion",
    label: "Dandelion",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "flower plant seeds blow wish clock weed",
    camera: { yaw: 0.35, pitch: 0.2, roll: 0, distance: 4.2 },
  },
  {
    id: "tulip",
    label: "Tulips",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "flower plant spring bulb petals holland",
    camera: { yaw: 0.45, pitch: 0.25, roll: 0, distance: 4.2 },
  },
  {
    id: "daisy",
    label: "Daisies",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "flower plant white petals meadow spring",
    camera: { yaw: 0.4, pitch: 0.3, roll: 0, distance: 4.2 },
  },
  {
    id: "lotus",
    label: "Lotus",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "flower plant water lily pad pond pink",
    camera: { yaw: 0.45, pitch: 0.62, roll: 0, distance: 3.9 },
  },
  {
    id: "mushroom",
    label: "Toadstool",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "fungus fly agaric red spots forest fairy",
    camera: { yaw: 0.45, pitch: 0.3, roll: 0, distance: 4.2 },
  },
  {
    id: "fern",
    label: "Fern",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "plant frond forest fiddlehead green",
    camera: { yaw: 0.45, pitch: 0.32, roll: 0, distance: 3.8 },
  },
  {
    id: "saguaro",
    label: "Saguaro cactus",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "plant cactus desert spines arms succulent",
    camera: { yaw: 0.45, pitch: 0.2, roll: 0, distance: 4.2 },
  },
  {
    id: "coral",
    label: "Coral reef",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "sea ocean reef anemone fish underwater",
    camera: { yaw: 0.45, pitch: 0.3, roll: 0, distance: 3.7 },
  },
  {
    id: "pinecone",
    label: "Pinecone",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "pine cone seed scales forest tree",
    camera: { yaw: 0.45, pitch: 0.25, roll: 0, distance: 4.2 },
  },
  {
    id: "acorn",
    label: "Acorns",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "oak nut seed leaf autumn squirrel",
    camera: { yaw: 0.35, pitch: 0.45, roll: 0, distance: 3.6 },
  },
  {
    id: "succulent",
    label: "Succulent",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "plant rosette echeveria pot cactus",
    camera: { yaw: 0.45, pitch: 0.55, roll: 0, distance: 4.2 },
  },
  {
    id: "bamboo",
    label: "Bamboo",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "plant grass stalks panda asia green",
    camera: { yaw: 0.45, pitch: 0.2, roll: 0, distance: 4.2 },
  },
  {
    id: "rocks",
    label: "Pebbles",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "rock stone pile cairn pebble beach",
    camera: { yaw: 0.45, pitch: 0.35, roll: 0, distance: 3.9 },
  },
  {
    id: "kelp",
    label: "Kelp",
    category: "nature",
    kind: "kit",
    pack: "nature",
    tags: "seaweed sea ocean underwater forest algae",
    camera: { yaw: 0.45, pitch: 0.2, roll: 0, distance: 4.2 },
  },

  // ---- Pack: elements ----
  // (entries for src/packs/elements.js go here)
  {
    id: "storm-cloud",
    label: "Storm cloud",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "weather rain lightning thunder cloud storm",
    camera: { yaw: 0.4, pitch: 0.2, roll: 0, distance: 4.0 },
  },
  {
    id: "lava-lamp",
    label: "Lava lamp",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "lamp wax blobs retro groovy glow light",
    camera: { yaw: 0.4, pitch: 0.2, roll: 0, distance: 4.2 },
  },
  {
    id: "snow-globe",
    label: "Snow globe",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "snow winter glass shake snowman christmas",
    camera: { yaw: 0.4, pitch: 0.25, roll: 0, distance: 4.2 },
  },
  {
    id: "volcano",
    label: "Volcano",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "lava eruption magma island mountain smoke fire",
    camera: { yaw: 0.45, pitch: 0.3, roll: 0, distance: 4.2 },
  },
  {
    id: "ice-statue",
    label: "Ice swan",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "ice sculpture swan melt frozen cold statue",
    camera: { yaw: 0.35, pitch: 0.18, roll: 0, distance: 3.8 },
  },
  {
    id: "candle",
    label: "Candle",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "flame wax light fire birthday glow",
    camera: { yaw: 0.45, pitch: 0.25, roll: 0, distance: 4.2 },
  },
  {
    id: "tornado",
    label: "Tornado",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "twister wind storm funnel weather cyclone",
    camera: { yaw: 0.45, pitch: 0.15, roll: 0, distance: 4.2 },
  },
  {
    id: "rainbow",
    label: "Rainbow",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "weather colours arc clouds sky",
    camera: { yaw: 0.2, pitch: 0.15, roll: 0, distance: 4.0 },
  },
  {
    id: "iceberg",
    label: "Iceberg",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "ice sea ocean arctic cold floe glacier",
    camera: { yaw: 0.45, pitch: 0.2, roll: 0, distance: 4.2 },
  },
  {
    id: "waterfall",
    label: "Waterfall",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "water river cliff falls mist pool",
    camera: { yaw: 0.45, pitch: 0.25, roll: 0, distance: 4.2 },
  },
  {
    id: "ocean-wave",
    label: "Ocean wave",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "sea surf wave curl barrel water beach",
    camera: { yaw: 0.6, pitch: 0.22, roll: 0, distance: 4.4 },
  },
  {
    id: "geyser",
    label: "Geyser",
    category: "weather",
    kind: "kit",
    pack: "elements",
    tags: "steam water hot spring eruption",
    camera: { yaw: 0.45, pitch: 0.25, roll: 0, distance: 4.2 },
  },

  // ---- Pack: food ----
  {
    id: "ice-cream",
    label: "Ice cream",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "cone scoop gelato waffle melt sprinkles cherry sweet dessert",
    camera: { yaw: 0.55, pitch: 0.3, roll: 0, distance: 3.9 },
  },
  {
    id: "watermelon",
    label: "Watermelon",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fruit melon wedge slice seeds summer picnic",
    camera: { yaw: 0.55, pitch: 0.34, roll: 0, distance: 4.1 },
  },
  {
    id: "birthday-cake",
    label: "Birthday cake",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "party candles flames blow out frosting sprinkles layers sweet dessert",
    camera: { yaw: 0.55, pitch: 0.36, roll: 0, distance: 4.2 },
  },
  {
    id: "popcorn",
    label: "Popcorn",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "cinema movie snack bucket pop kernels butter",
    camera: { yaw: 0.55, pitch: 0.34, roll: 0, distance: 4.2 },
  },
  {
    id: "jelly",
    label: "Jelly",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "jello gelatin wobble wobbly dessert fruit pudding",
    camera: { yaw: 0.55, pitch: 0.4, roll: 0, distance: 4.1 },
  },
  {
    id: "pancakes",
    label: "Pancakes",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "breakfast stack syrup butter flip hotcakes",
    camera: { yaw: 0.55, pitch: 0.42, roll: 0, distance: 4.1 },
  },
  {
    id: "cupcake",
    label: "Cupcake",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fairy cake muffin frosting swirl sprinkles cherry sweet",
    camera: { yaw: 0.55, pitch: 0.3, roll: 0, distance: 4.0 },
  },
  {
    id: "lollipop",
    label: "Lollipop",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "candy swirl sweet rainbow stick sucker",
    camera: { yaw: 0.3, pitch: 0.2, roll: 0, distance: 4.0 },
  },
  {
    id: "candy-cane",
    label: "Candy cane",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "christmas peppermint stripes candy sweet bow",
    camera: { yaw: 0.3, pitch: 0.2, roll: 0, distance: 4.0 },
  },
  {
    id: "macarons",
    label: "Macarons",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "french biscuits pastel almond sweet stack",
    camera: { yaw: 0.55, pitch: 0.3, roll: 0, distance: 4.1 },
  },
  {
    id: "gummy-bear",
    label: "Gummy bear",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "candy jelly sweet bear chewy squish",
    camera: { yaw: 0.35, pitch: 0.2, roll: 0, distance: 4.0 },
  },
  {
    id: "pretzel",
    label: "Pretzel",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "bread knot salt baked snack bakery",
    camera: { yaw: 0.3, pitch: 0.25, roll: 0, distance: 4.1 },
  },
  {
    id: "croissant",
    label: "Croissant",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "pastry bakery breakfast french flaky butter",
    camera: { yaw: 0.45, pitch: 0.95, roll: 0, distance: 3.9 },
  },
  {
    id: "pizza",
    label: "Pizza",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "pepperoni margherita cheese slice italian basil dinner",
    camera: { yaw: 0.55, pitch: 0.72, roll: 0, distance: 3.9 },
  },
  {
    id: "burger",
    label: "Burger",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "hamburger cheeseburger bun sesame lettuce tomato cheese patty",
    camera: { yaw: 0.55, pitch: 0.3, roll: 0, distance: 4.0 },
  },
  {
    id: "sushi",
    label: "Sushi",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "japanese nigiri maki roll salmon tuna rice chopsticks wasabi",
    camera: { yaw: 0.45, pitch: 0.62, roll: 0, distance: 3.7 },
  },
  {
    id: "taco",
    label: "Taco",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "mexican shell lettuce cheese tomato beef",
    camera: { yaw: 0.4, pitch: 0.3, roll: 0, distance: 3.9 },
  },
  {
    id: "egg",
    label: "Boiled egg",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "breakfast egg cup yolk toast soldiers crack",
    camera: { yaw: 0.45, pitch: 0.3, roll: 0, distance: 4.1 },
  },
  {
    id: "coffee",
    label: "Coffee",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "latte cappuccino cup saucer drink steam cafe art",
    camera: { yaw: 0.55, pitch: 0.58, roll: 0, distance: 4.0 },
  },
  {
    id: "apple",
    label: "Apple",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fruit red green golden leaf orchard",
    camera: { yaw: 0.55, pitch: 0.3, roll: 0, distance: 4.1 },
  },
  {
    id: "banana",
    label: "Bananas",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fruit bunch yellow tropical",
    camera: { yaw: 0.3, pitch: 0.35, roll: 0, distance: 4.2 },
  },
  {
    id: "orange",
    label: "Orange",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fruit citrus segments half juicy leaf",
    camera: { yaw: 0.55, pitch: 0.36, roll: 0, distance: 4.2 },
  },
  {
    id: "kiwi",
    label: "Kiwi",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fruit kiwifruit green seeds half fuzzy",
    camera: { yaw: 0.55, pitch: 0.36, roll: 0, distance: 4.2 },
  },
  {
    id: "pineapple",
    label: "Pineapple",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fruit tropical crown leaves spiky",
    camera: { yaw: 0.55, pitch: 0.25, roll: 0, distance: 4.1 },
  },
  {
    id: "cherries",
    label: "Cherries",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fruit cherry pair stems red glossy",
    camera: { yaw: 0.35, pitch: 0.25, roll: 0, distance: 4.1 },
  },
  {
    id: "grapes",
    label: "Grapes",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fruit bunch vine purple green leaf",
    camera: { yaw: 0.45, pitch: 0.25, roll: 0, distance: 4.1 },
  },
  {
    id: "avocado",
    label: "Avocado",
    category: "food",
    kind: "kit",
    pack: "food",
    tags: "fruit halves stone pit green guacamole",
    camera: { yaw: 0.55, pitch: 0.45, roll: 0, distance: 4.2 },
  },

  // ---- Pack: playthings ----
  {
    id: "bricks",
    label: "Building bricks",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "blocks studs stack build construction plastic",
    camera: { yaw: 0.6, pitch: 0.42, roll: 0, distance: 4.4 },
  },
  {
    id: "rubber-duck",
    label: "Rubber duck",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "bath duckie yellow squeak",
    camera: { yaw: 0.95, pitch: 0.22, roll: 0, distance: 4.4 },
  },
  {
    id: "spinning-top",
    label: "Spinning top",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "spin whirl gyroscope precession",
    camera: { yaw: 0.5, pitch: 0.3, roll: 0, distance: 4.5 },
  },
  {
    id: "dice",
    label: "Dice",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "die d6 d20 roll pips game chance",
    camera: { yaw: 0.45, pitch: 0.5, roll: 0, distance: 4.4 },
  },
  {
    id: "newtons-cradle",
    label: "Newton's cradle",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "pendulum balls swing desk physics momentum",
    camera: { yaw: 0.35, pitch: 0.25, roll: 0, distance: 4.4 },
  },
  {
    id: "teddy-bear",
    label: "Teddy bear",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "bear plush soft cuddly stuffed",
    camera: { yaw: 0.3, pitch: 0.18, roll: 0, distance: 4.5 },
  },
  {
    id: "yo-yo",
    label: "Yo-yo",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "yoyo string spin throw",
    camera: { yaw: 0.35, pitch: 0.12, roll: 0, distance: 3.9 },
  },
  {
    id: "puzzle-cube",
    label: "Puzzle cube",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "twist cube colours puzzle 3x3",
    camera: { yaw: 0.62, pitch: 0.5, roll: 0, distance: 7.4 },
  },
  {
    id: "spring-toy",
    label: "Spring toy",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "coil slinky rainbow stairs walk",
    camera: { yaw: 0.25, pitch: 0.3, roll: 0, distance: 4.4 },
  },
  {
    id: "kite",
    label: "Kite",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "wind fly diamond tail string sky",
    camera: { yaw: 0.2, pitch: 0.1, roll: 0, distance: 4.4 },
  },
  {
    id: "paper-plane",
    label: "Paper plane",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "paper aeroplane airplane dart fold fly",
    camera: { yaw: 0.7, pitch: 0.42, roll: 0, distance: 3.6 },
  },
  {
    id: "origami-crane",
    label: "Origami crane",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "paper fold bird japan crane",
    camera: { yaw: 0.35, pitch: 0.3, roll: 0, distance: 3.7 },
  },
  {
    id: "balloon-dog",
    label: "Balloon dog",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "balloon animal twist party pop",
    camera: { yaw: 0.2, pitch: 0.2, roll: 0, distance: 4.4 },
  },
  {
    id: "soap-bubbles",
    label: "Soap bubbles",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "bubble wand iridescent float blow",
    camera: { yaw: 0.2, pitch: 0.15, roll: 0, distance: 4.4 },
  },
  {
    id: "robot",
    label: "Wind-up robot",
    category: "toys",
    kind: "kit",
    pack: "playthings",
    tags: "robot tin clockwork key antenna retro",
    camera: { yaw: 0.45, pitch: 0.2, roll: 0, distance: 4.5 },
  },
  {
    id: "chess-set",
    label: "Chess set",
    category: "toys",
    kind: "kit",
    pack: "games",
    tags: "chess game board pieces king queen knight opera morphy",
    camera: { yaw: 0.55, pitch: 0.6, roll: 0, distance: 3.7 },
  },

  // ---- Pack: maths ----
  {
    id: "lorenz",
    label: "Lorenz attractor",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "chaos butterfly strange attractor curve differential equations",
    camera: { yaw: 0.15, pitch: 0.12, roll: 0, distance: 4.2 },
  },
  {
    id: "mobius",
    label: "Möbius strip",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "mobius moebius band one side twist topology surface",
    camera: { yaw: 0.9, pitch: 0.22, roll: 0, distance: 4.3 },
  },
  {
    id: "klein-bottle",
    label: "Klein bottle",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "topology surface glass bottle non-orientable",
    camera: { yaw: 0.5, pitch: 0.2, roll: 0, distance: 4.4 },
  },
  {
    id: "menger-sponge",
    label: "Menger sponge",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "fractal cube holes sponge recursive",
    camera: { yaw: 0.62, pitch: 0.5, roll: 0, distance: 7.2 },
  },
  {
    id: "hypercube",
    label: "Hypercube",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "tesseract 4d four dimensions cube projection",
    camera: { yaw: 0.55, pitch: 0.35, roll: 0, distance: 6.4 },
  },
  {
    id: "torus-knot",
    label: "Torus knot",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "knot trefoil topology tube curve",
    camera: { yaw: 0.2, pitch: 0.3, roll: 0, distance: 4.2 },
  },
  {
    id: "gyroid",
    label: "Gyroid",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "minimal surface triply periodic labyrinth",
    camera: { yaw: 0.62, pitch: 0.45, roll: 0, distance: 6.8 },
  },
  {
    id: "mandelbulb",
    label: "Mandelbulb",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "fractal 3d mandelbrot bulb",
    camera: { yaw: 0.5, pitch: 0.35, roll: 0, distance: 4.4 },
  },
  {
    id: "sierpinski",
    label: "Sierpinski tetrahedron",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "fractal triangle pyramid tetrix recursive",
    camera: { yaw: 0.5, pitch: 0.3, roll: 0, distance: 4.4 },
  },
  {
    id: "platonic",
    label: "Platonic solids",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "polyhedron tetrahedron cube octahedron dodecahedron icosahedron geometry",
    camera: { yaw: 0.5, pitch: 0.35, roll: 0, distance: 5.2 },
  },
  {
    id: "seashell-spiral",
    label: "Seashell spiral",
    category: "maths",
    kind: "kit",
    pack: "maths",
    tags: "spiral shell logarithmic conch snail growth",
    camera: { yaw: 0.5, pitch: 0.85, roll: 0, distance: 3.8 },
  },

  // ---- Pack: objects ----
  {
    id: "book",
    label: "Storybook",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "book pages read story hardcover open close flip",
    camera: { yaw: 0.25, pitch: 0.78, roll: 0, distance: 3.9 },
  },
  {
    id: "laptop",
    label: "Laptop",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "computer notebook screen keyboard open close",
    camera: { yaw: 0.45, pitch: 0.32, roll: 0, distance: 4.6 },
  },
  {
    id: "music-box",
    label: "Music box",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "ballerina dancer jewellery box lid tune",
    camera: { yaw: 0.4, pitch: 0.35, roll: 0, distance: 4.6 },
  },
  {
    id: "clock",
    label: "Alarm clock",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "clock time bells alarm ring hands",
    camera: { yaw: 0.3, pitch: 0.12, roll: 0, distance: 4.4 },
  },
  {
    id: "gift-box",
    label: "Gift box",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "present birthday ribbon bow surprise confetti",
    camera: { yaw: 0.5, pitch: 0.38, roll: 0, distance: 4.8 },
  },
  {
    id: "umbrella",
    label: "Umbrella",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "rain parasol canopy open close",
    camera: { yaw: 0.4, pitch: 0.3, roll: 0, distance: 4.3 },
  },
  {
    id: "desk-fan",
    label: "Desk fan",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "fan blades spin breeze oscillating retro",
    camera: { yaw: 0.35, pitch: 0.2, roll: 0, distance: 4.4 },
  },
  {
    id: "lamp",
    label: "Desk lamp",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "lamp light bulb switch anglepoise",
    camera: { yaw: 0.2, pitch: 0.25, roll: 0, distance: 4.4 },
  },
  {
    id: "potion-bottle",
    label: "Potion bottle",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "magic flask glow cork bubbles wizard",
    camera: { yaw: 0.4, pitch: 0.2, roll: 0, distance: 4.4 },
  },
  {
    id: "telescope",
    label: "Telescope",
    category: "objects",
    kind: "kit",
    pack: "objects",
    tags: "brass spyglass tripod stars astronomy extend",
    camera: { yaw: 0.35, pitch: 0.2, roll: 0, distance: 4.4 },
  },

  // ---- Pack: medieval ----
  {
    id: "sword-in-stone",
    label: "Sword in the stone",
    category: "medieval",
    kind: "kit",
    pack: "medieval",
    tags: "legend king blade rock moss pull magic knight",
    camera: { yaw: 0.55, pitch: 0.28, roll: 0, distance: 4.5 },
  },
  {
    id: "shield",
    label: "Heraldic shield",
    category: "medieval",
    kind: "kit",
    pack: "medieval",
    tags: "knight heater coat of arms heraldry crest armour",
    camera: { yaw: 0.3, pitch: 0.2, roll: 0, distance: 5 },
  },
  {
    id: "bow-and-target",
    label: "Bow and target",
    category: "medieval",
    kind: "kit",
    pack: "medieval",
    tags: "archery arrow bullseye longbow shoot straw",
    camera: { yaw: 0.8, pitch: 0.3, roll: 0, distance: 3.9 },
  },
  {
    id: "trebuchet",
    label: "Trebuchet",
    category: "medieval",
    kind: "kit",
    pack: "medieval",
    tags: "siege engine catapult castle launch stone counterweight",
    camera: { yaw: 0.55, pitch: 0.28, roll: 0, distance: 4.5 },
  },
  {
    id: "crossbow",
    label: "Crossbow",
    category: "medieval",
    kind: "kit",
    pack: "medieval",
    tags: "bolt string archery shoot",
    camera: { yaw: 0.55, pitch: 0.45, roll: 0, distance: 3.6 },
  },
  {
    id: "knights-helmet",
    label: "Knight's helmet",
    category: "medieval",
    kind: "kit",
    pack: "medieval",
    tags: "armour helm visor plume feathers steel",
  },
  {
    id: "crown",
    label: "Crown",
    category: "medieval",
    kind: "kit",
    pack: "medieval",
    tags: "king queen royal gold gems jewels pearls ermine",
    camera: { yaw: 0.55, pitch: 0.42, roll: 0, distance: 5 },
  },
  {
    id: "dragon-egg",
    label: "Dragon egg",
    category: "medieval",
    kind: "kit",
    pack: "medieval",
    tags: "fantasy baby dragon hatch nest scales",
    camera: { yaw: 0.55, pitch: 0.28, roll: 0, distance: 4.6 },
  },
  {
    id: "wizards-orb",
    label: "Wizard's orb",
    category: "medieval",
    kind: "kit",
    pack: "medieval",
    tags: "magic crystal ball fantasy spell swirl sparkles",
    camera: { yaw: 0.55, pitch: 0.28, roll: 0, distance: 4.4 },
  },

  // ---- Pack: animals ----
  {
    id: "jellyfish",
    label: "Jellyfish",
    category: "animals",
    kind: "kit",
    pack: "animals",
    tags: "sea ocean jelly tentacles glow pulse moon nettle",
  },
  {
    id: "fish-school",
    label: "School of fish",
    category: "animals",
    kind: "kit",
    pack: "animals",
    tags: "sea ocean shoal sardines swim bubbles tropical",
    camera: { yaw: 0.55, pitch: 0.28, roll: 0, distance: 4.4 },
  },
  {
    id: "butterfly",
    label: "Butterfly",
    category: "animals",
    kind: "kit",
    pack: "animals",
    tags: "insect wings flutter monarch morpho swallowtail bug",
    camera: { yaw: 0.25, pitch: 0.22, roll: 0, distance: 5 },
  },
  {
    id: "pufferfish",
    label: "Pufferfish",
    category: "animals",
    kind: "kit",
    pack: "animals",
    tags: "sea ocean blowfish puff spines inflate fish",
  },
  {
    id: "nautilus",
    label: "Nautilus",
    category: "animals",
    kind: "kit",
    pack: "animals",
    tags: "sea ocean shell spiral chambers tentacles golden ratio",
    camera: { yaw: 0.25, pitch: 0.22, roll: 0, distance: 5 },
  },
  {
    id: "ladybug",
    label: "Ladybug",
    category: "animals",
    kind: "kit",
    pack: "animals",
    tags: "ladybird insect beetle bug spots wings fly",
    camera: { yaw: 0.6, pitch: 0.5, roll: 0, distance: 5 },
  },
  {
    id: "snail",
    label: "Snail",
    category: "animals",
    kind: "kit",
    pack: "animals",
    tags: "garden shell spiral slow slime hide",
    camera: { yaw: 0.55, pitch: 0.28, roll: 0, distance: 4.2 },
  },
  {
    id: "octopus",
    label: "Octopus",
    category: "animals",
    kind: "kit",
    pack: "animals",
    tags: "sea ocean tentacles arms ink suckers",
    camera: { yaw: 0.55, pitch: 0.4, roll: 0, distance: 5 },
  },
  {
    id: "starfish",
    label: "Starfish",
    category: "animals",
    kind: "kit",
    pack: "animals",
    tags: "sea star ocean beach arms",
    camera: { yaw: 0.55, pitch: 0.8, roll: 0, distance: 5 },
  },
  {
    id: "sea-urchin",
    label: "Sea urchin",
    category: "animals",
    kind: "kit",
    pack: "animals",
    tags: "sea ocean spines spiky uni",
  },
  {
    id: "frog",
    label: "Frog",
    category: "animals",
    kind: "kit",
    pack: "animals",
    tags: "pond amphibian toad hop green",
  },
  {
    id: "penguin",
    label: "Penguin",
    category: "animals",
    kind: "kit",
    pack: "animals",
    tags: "bird ice antarctic flippers waddle",
  },
  {
    id: "owl",
    label: "Owl",
    category: "animals",
    kind: "kit",
    pack: "animals",
    tags: "bird night hoot feathers branch wise",
  },

  // ---- Pack: holidays ----
  {
    id: "jack-o-lantern",
    label: "Jack-o'-lantern",
    category: "holidays",
    kind: "kit",
    pack: "holidays",
    tags: "halloween pumpkin carved candle glow autumn",
    camera: { yaw: 0.45, pitch: 0.25, roll: 0, distance: 5 },
  },
  {
    id: "snowman",
    label: "Snowman",
    category: "holidays",
    kind: "kit",
    pack: "holidays",
    tags: "winter snow melt carrot scarf hat christmas",
    camera: { yaw: 0.55, pitch: 0.25, roll: 0, distance: 4.4 },
  },
  {
    id: "fireworks",
    label: "Fireworks",
    category: "holidays",
    kind: "kit",
    pack: "holidays",
    tags: "new year celebration rocket sparks burst diwali festival",
    camera: { yaw: 0.35, pitch: 0.12, roll: 0, distance: 3.9 },
  },
  {
    id: "decorated-tree",
    label: "Decorated tree",
    category: "holidays",
    kind: "kit",
    pack: "holidays",
    tags: "christmas evergreen fir baubles lights star presents winter",
  },
  {
    id: "patterned-egg",
    label: "Patterned egg",
    category: "holidays",
    kind: "kit",
    pack: "holidays",
    tags: "easter nowruz spring pysanka painted decorated",
  },
  {
    id: "paper-lantern",
    label: "Paper lantern",
    category: "holidays",
    kind: "kit",
    pack: "holidays",
    tags: "lunar new year mid-autumn festival glow hanging tassel",
  },
  {
    id: "diya",
    label: "Diya",
    category: "holidays",
    kind: "kit",
    pack: "holidays",
    tags: "diwali oil lamp flame light rangoli clay festival",
    camera: { yaw: 0.55, pitch: 0.4, roll: 0, distance: 4.3 },
  },
  {
    id: "menorah",
    label: "Menorah",
    category: "holidays",
    kind: "kit",
    pack: "holidays",
    tags: "hanukkah hanukkiah candles festival of lights brass",
    camera: { yaw: 0.3, pitch: 0.18, roll: 0, distance: 4.6 },
  },

  // ---- Pack: music ----
  {
    id: "guitar",
    label: "Acoustic guitar",
    category: "music",
    kind: "kit",
    pack: "music",
    tags: "instrument strings strum acoustic sunburst",
    camera: { yaw: 0.15, pitch: 0.2, roll: 0, distance: 4.2 },
  },
  {
    id: "drum",
    label: "Snare drum",
    category: "music",
    kind: "kit",
    pack: "music",
    tags: "instrument percussion sticks beat hit",
    camera: { yaw: 0.5, pitch: 0.42, roll: 0, distance: 5 },
  },
  {
    id: "xylophone",
    label: "Xylophone",
    category: "music",
    kind: "kit",
    pack: "music",
    tags: "instrument rainbow bars mallet toy glockenspiel",
    camera: { yaw: 0.45, pitch: 0.5, roll: 0, distance: 4.1 },
  },

  // ---- Pack: vehicles ----
  {
    id: "rocket",
    label: "Rocket",
    category: "vehicles",
    kind: "kit",
    pack: "vehicles",
    tags: "space launch pad blast off lift off fins spaceship",
    camera: { yaw: 0.55, pitch: 0.28, roll: 0, distance: 4.3 },
  },
  {
    id: "helicopter",
    label: "Helicopter",
    category: "vehicles",
    kind: "kit",
    pack: "vehicles",
    tags: "chopper rotor fly helipad aircraft",
    camera: { yaw: 0.55, pitch: 0.3, roll: 0, distance: 4.4 },
  },
  {
    id: "hot-air-balloon",
    label: "Hot-air balloon",
    category: "vehicles",
    kind: "kit",
    pack: "vehicles",
    tags: "balloon basket burner float sky flight",
    camera: { yaw: 0.55, pitch: 0.22, roll: 0, distance: 4.5 },
  },
  {
    id: "steam-train",
    label: "Steam train",
    category: "vehicles",
    kind: "kit",
    pack: "vehicles",
    tags: "locomotive engine railway track smoke choo choo tender",
    camera: { yaw: 0.6, pitch: 0.3, roll: 0, distance: 3.9 },
  },
  {
    id: "ocean-liner",
    label: "Ocean liner",
    category: "vehicles",
    kind: "kit",
    pack: "vehicles",
    tags: "ship boat steamship funnels sea cruise",
    camera: { yaw: 0.62, pitch: 0.3, roll: 0, distance: 3.5 },
  },

  {
    id: "sports-car",
    label: "Sports car",
    category: "vehicles",
    kind: "kit",
    pack: "vehicles",
    tags: "car racing coupe fast wheels spoiler",
    camera: { yaw: 0.6, pitch: 0.3, roll: 0, distance: 2.85 },
  },
  {
    id: "bus",
    label: "Bus",
    category: "vehicles",
    kind: "kit",
    pack: "vehicles",
    tags: "school bus double decker coach wheels",
    camera: { yaw: 0.6, pitch: 0.28, roll: 0, distance: 4.2 },
  },
  {
    id: "propeller-plane",
    label: "Propeller plane",
    category: "vehicles",
    kind: "kit",
    pack: "vehicles",
    tags: "biplane aeroplane airplane aircraft pilot prop fly loop",
    camera: { yaw: 0.6, pitch: 0.3, roll: 0, distance: 4.3 },
  },
  {
    id: "jet",
    label: "Jet airliner",
    category: "vehicles",
    kind: "kit",
    pack: "vehicles",
    tags: "aeroplane airplane aircraft plane passenger fly wings engines",
    camera: { yaw: 0.6, pitch: 0.35, roll: 0, distance: 4.2 },
  },
  {
    id: "sailboat",
    label: "Sailboat",
    category: "vehicles",
    kind: "kit",
    pack: "vehicles",
    tags: "yacht boat sail sea mast wind",
    camera: { yaw: 0.55, pitch: 0.28, roll: 0, distance: 4.4 },
  },
  {
    id: "submarine",
    label: "Submarine",
    category: "vehicles",
    kind: "kit",
    pack: "vehicles",
    tags: "sub underwater periscope bubbles sea",
    camera: { yaw: 0.55, pitch: 0.25, roll: 0, distance: 4.2 },
  },
  {
    id: "bicycle",
    label: "Bicycle",
    category: "vehicles",
    kind: "kit",
    pack: "vehicles",
    tags: "bike cycle wheels pedals bell",
    camera: { yaw: 0.6, pitch: 0.25, roll: 0, distance: 4.1 },
  },
  {
    id: "tractor",
    label: "Tractor",
    category: "vehicles",
    kind: "kit",
    pack: "vehicles",
    tags: "farm field wheels exhaust",
    camera: { yaw: 0.6, pitch: 0.3, roll: 0, distance: 4.4 },
  },
  {
    id: "ufo",
    label: "Flying saucer",
    category: "vehicles",
    kind: "kit",
    pack: "vehicles",
    tags: "ufo alien spaceship beam cow space",
    camera: { yaw: 0.55, pitch: 0.25, roll: 0, distance: 4.5 },
  },

  // ---- Pack: landmarks ----
  {
    id: "eiffel-tower",
    label: "Eiffel Tower",
    category: "landmarks",
    kind: "kit",
    pack: "landmarks",
    tags: "paris france tower iron lattice",
    camera: { yaw: 0.55, pitch: 0.22, roll: 0, distance: 4.2 },
  },
  {
    id: "washington-monument",
    label: "Washington Monument",
    category: "landmarks",
    kind: "kit",
    pack: "landmarks",
    tags: "obelisk usa washington dc flags",
    camera: { yaw: 0.55, pitch: 0.22, roll: 0, distance: 4.0 },
  },
  {
    id: "pyramids",
    label: "Pyramids of Giza",
    category: "landmarks",
    kind: "kit",
    pack: "landmarks",
    tags: "egypt giza sphinx desert ancient pharaoh",
    camera: { yaw: 0.55, pitch: 0.32, roll: 0, distance: 3.4 },
  },
  {
    id: "supertall",
    label: "Twisting supertall",
    category: "landmarks",
    kind: "kit",
    pack: "landmarks",
    tags: "skyscraper tower city glass modern building",
    camera: { yaw: 0.55, pitch: 0.22, roll: 0, distance: 4.1 },
  },
  {
    id: "lighthouse",
    label: "Lighthouse",
    category: "landmarks",
    kind: "kit",
    pack: "landmarks",
    tags: "beacon coast sea rocks beam light",
    camera: { yaw: 0.55, pitch: 0.28, roll: 0, distance: 4.3 },
  },
  {
    id: "statue-of-liberty",
    label: "Statue of Liberty",
    category: "landmarks",
    kind: "kit",
    pack: "landmarks",
    tags: "new york usa torch crown statue harbour",
    camera: { yaw: 0.55, pitch: 0.25, roll: 0, distance: 4.0 },
  },
  {
    id: "white-house",
    label: "White House",
    category: "landmarks",
    kind: "kit",
    pack: "landmarks",
    tags: "washington usa president house columns portico",
    camera: { yaw: 0.55, pitch: 0.38, roll: 0, distance: 3.9 },
  },
  {
    id: "leaning-tower",
    label: "Leaning Tower of Pisa",
    category: "landmarks",
    kind: "kit",
    pack: "landmarks",
    tags: "pisa italy lean tower bell",
    camera: { yaw: 0.55, pitch: 0.22, roll: 0, distance: 4.2 },
  },
  {
    id: "colosseum",
    label: "Colosseum",
    category: "landmarks",
    kind: "kit",
    pack: "landmarks",
    tags: "rome italy amphitheatre arena ancient",
    camera: { yaw: 0.55, pitch: 0.62, roll: 0, distance: 3.6 },
  },
  {
    id: "parthenon",
    label: "Parthenon",
    category: "landmarks",
    kind: "kit",
    pack: "landmarks",
    tags: "athens greece temple acropolis columns ancient",
    camera: { yaw: 0.55, pitch: 0.35, roll: 0, distance: 3.8 },
  },
  {
    id: "stonehenge",
    label: "Stonehenge",
    category: "landmarks",
    kind: "kit",
    pack: "landmarks",
    tags: "stones circle england ancient trilithon",
    camera: { yaw: 0.55, pitch: 0.55, roll: 0, distance: 3.6 },
  },
  {
    id: "big-ben",
    label: "Big Ben",
    category: "landmarks",
    kind: "kit",
    pack: "landmarks",
    tags: "clock tower london england elizabeth tower bell",
    camera: { yaw: 0.55, pitch: 0.22, roll: 0, distance: 4.2 },
  },
  {
    id: "taj-mahal",
    label: "Taj Mahal",
    category: "landmarks",
    kind: "kit",
    pack: "landmarks",
    tags: "india agra dome minarets marble",
    camera: { yaw: 0.4, pitch: 0.32, roll: 0, distance: 3.8 },
  },
  {
    id: "castle",
    label: "Castle",
    category: "landmarks",
    kind: "kit",
    pack: "landmarks",
    tags: "medieval towers drawbridge moat battlements",
    camera: { yaw: 0.55, pitch: 0.42, roll: 0, distance: 4.0 },
  },
  {
    id: "pagoda",
    label: "Pagoda",
    category: "landmarks",
    kind: "kit",
    pack: "landmarks",
    tags: "japan temple tiers roofs bells",
    camera: { yaw: 0.55, pitch: 0.3, roll: 0, distance: 4.3 },
  },
  {
    id: "windmill",
    label: "Windmill",
    category: "landmarks",
    kind: "kit",
    pack: "landmarks",
    tags: "netherlands dutch mill sails tulips",
    camera: { yaw: 0.55, pitch: 0.28, roll: 0, distance: 4.3 },
  },
];

export function findToy(id) {
  return TOYS.find((t) => t.id === id) || null;
}

export function categoryLabel(id) {
  return CATEGORIES.find((c) => c.id === id)?.label || "";
}

// Categories that have at least one toy, in shelf order.
export function shelfCategories() {
  return CATEGORIES.filter((c) => TOYS.some((t) => t.category === c.id));
}

// Lower-case, accent-free text for search matching.
export function foldText(text) {
  return String(text || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase();
}

// Toys matching a search: every word must appear in the label, the
// category name or the toy's search words. Label matches come first.
export function searchToys(query, toys = TOYS) {
  const words = foldText(query).split(/\s+/).filter(Boolean);
  if (!words.length) return toys.slice();
  const scored = [];
  for (const t of toys) {
    const label = foldText(t.label);
    const hay = `${label} ${foldText(categoryLabel(t.category))} ${foldText(t.tags)} ${t.id}`;
    if (!words.every((w) => hay.includes(w))) continue;
    const score = words.reduce(
      (n, w) => n + (label.startsWith(w) ? 3 : label.includes(w) ? 2 : 0),
      0,
    );
    scored.push({ t, score });
  }
  return scored.sort((a, b) => b.score - a.score).map((s) => s.t);
}

// Resolves an asset path against the Splashery root (works from the app,
// the embed page and the custom element on another site).
export const ROOT = new URL("../", import.meta.url);

export function assetURL(path) {
  return new URL(path, ROOT).href;
}

export function thumbURL(toy) {
  return assetURL(`assets/toys/${toy.id}/thumb.webp`);
}
